dwarf-fortress.json
Dwarf fortress is a game about building a fortress full of dwarves :smile:
=> Add dwarf fortress

openrct2.json
This should, together with #6, close #1
=> Add OpenRCT2 v0.2.1

endless-sky, endless-sky.json
i came here to make this PR, only to realize @r15ch13 had already made this suggestion in #1.
(btw, did you happen to get that tip from a certain devrant post?)
anyways, here's a working endless sky manifest.
=> Add endless-sky v0.9.8

taisei.json
Please check the license, not 100% confident about it
=> Add taisei v1.2

bucket/openra.json
=> Add OpenRA (open-source implementation of Red Alert 1)

bucket/mindustry-server.json, bucket/mindustry.json
This was previously proposed in [[Request] Mindustry](https://github.com/Calinou/scoop-games/issues/24)
=> Add Mindustry and Mindustry-server

bucket/sw-exporter.json
See Also:
* https://swarfarm.com/
* https://github.com/Xzandro/sw-exporter
=> sw-exporter: Update to 0.0.26

bucket/amidst.json, bucket/mcedit2.json, bucket/minutor.json
Homepage of **MCEdit2**: https://www.mcedit.net/
Homepage of **Amidst**: https://github.com/toolbox4minecraft/amidst
Homepage of **Minutor**: http://seancode.com/minutor/
=> Add Minecraft-related tools: Amidst, Minutor, MCEdit2

bucket/wesnoth.json
=> wesnoth: add checkver and autoupdate

bucket/freeciv.json
**FreeCiv** ([homepage](http://www.freeciv.org/)) is a open-source empire-building strategy game.
=> Freeciv: Add version 2.6.0

bucket/runebook.json
Requested in https://github.com/lukesampson/scoop-extras/issues/2240
Official page for Runebook: https://runebook.app/
=> runebook: Add version 1.8.9

bucket/dwarf-fortress-lnp.json
This is Peridexis Errant's starter pack for dwarf fortress :)
=> Add the Dwarf Fortress Lazy Newb Pack

bucket/umoria.json
This adds umoria, which is a roguelike based on Lord of the Rings
=> Add umoria

bucket/angband.json
This adds angband, which is a roguelike derived from umoria
=> Add angband.

bucket/nethack.json
This adds nethack, which is another roguelike
=> Add nethack

bucket/adom.json
This adds the free ascii version of the roguelike Ancient Domains of Mystery
=> Add adom (ascii).

bucket/brogue.json
=> Add brogue

bucket/openttd.json
=> openttd: Update to version 1.9.2

bucket/lambdahack.json
Happy Hacktoberfest, @Calinou! :smile:
=> Add lambdahack

appveyor.yml
=> fix(appveyor): PS 6 builds

bucket/dolphin-dev.json
For some reason the url scheme changed and some random characters were added.
=> dolphin-dev: Fix autoupdate

bucket/warzone2100.json
=> warzone2100: fix url

bucket/vortex.json
Hey there...
This is my first contribution. I'm not really sure how to test it locally to see if it works.
=> vortex: Update to version 1.2.10

bucket/minecraft.json, bucket/runebook.json, bucket/trenchbroom.json, bucket/xmoto.json
To clear out https://github.com/ScoopInstaller/Main/issues/773
=> Fix various homepage URLs

bucket/warsow.json
URL is down, I updated URL from warsow.net
=> warsow: Update download URL as the previous one is down

bucket/eduke32.json
* Fix checkver regex for latest synthesis versions
* Persist settings files and autoload folder
* Update to version 20200515-8937-74da38c9c
=> eduke32: Implement various manifest improvements

bucket/minecraft.json
I've tested this, and it [seems to work](https://github.com/TheRandomLabs/Scoop-Bucket/commit/70ab7a3a492fdb00bea86a97b130657de1ed72a2). Note that this is for the launcher, and not the actual game itself. :)
=> minecraft: Add autoupdate

bucket/undertale-mod-tool.json
Changelog:
* Edit (7/7/20): Fix to ImportGML experimental script, reuploaded ZIP
* Edit (7/11/20): Fix to ImportGraphics_v2 experimental script, reuploaded ZIP
=> undertale-mod-tool: Update to version 0.3.0-6

bucket/minetest.json
User screenshots should be considered valuable and persist.
=> minetest: Make the screenshots directory persistent

bucket/sil.json
A manifest for a roguelike game Sil (http://www.amirrorclear.net/flowers/game/sil/)
=> Add Sil version 1.3.0

bucket/melonds.json
=> melonjs: Update to version 0.9

bucket/widelands.json
=> Add Widelands 21

bucket/sauerbraten.json
Cube 2: Sauerbraten was recently updated for the first time since 2013, this PR updates the manifest for that
=> sauerbraten: Update to version 2020-edition

bucket/mcrcon.json
=> mcrcon: Add version 0.7.1

bucket/minecraft.json
Resolves #146. Thanks for waiting, exams got in the way. 😄
=> minecraft: Fix launch error

bucket/undertale-mod-tool.json
=> undertale-mod-tool: Update to version 0.3.5.4

bucket/amulet-map-editor.json
- From lukesampson/scoop-extras#5282
- Closes lukesampson/scoop-extras#5281
=> amulet-map-editor: Add version 0.7.2.8

bucket/undertale-mod-tool.json
- removed unnecessary architecture difference (the release is only one)
- added persist
=> undertale-mod-tool: manifest cleanup and added persist conf file

bucket/cxbx-reloaded.json
There are no releases yet, so I used the timestamp as a version.
=> cxbx-reloaded: Add version 0.2021.0202.1246

bucket/ryujinx-dev.json
=> Ryujinx: Add 1.0.6551

bucket/betterjoy.json
=> BetterJoy: Add v6.4b

bucket/duckstation.json
=> Duckstation: Add nightly

bucket/triplea.json
Closes #152 
Persistence may be hit or miss on this one, can't find a settings file anywhere.
=> triplea: Add 2.5.22294 

bucket/powdertoy.json
=> powdertoy: Add 95.0

bucket/openmw-nightly.json
A new fix for openmw-nightly to fit the artifacts folder structure.
=> openmw-nightly: Fix archive name

bucket/doom-retro.json
=> doom-retro: Add 4.0.4

bucket/ryujinx-dev.json
New changes in Ryujinx have changed how to activate portable mode.
[https://github.com/Ryujinx/Ryujinx/pull/1885]()
=> ryujinx-dev: Update persistence

bucket/vkquake2.json
Hopefully this works better for a PR.
EDIT: Changed hash to lower case letters for easier readability.
=> vkquake2: Add version 1.5.7

bucket/fbneo.json
FinalBurn Neo is an emulator for arcade games & select consoles, a more focused alternative to MAME and used as the emulator of choice for projects like Fightcade.
=> fbneo: Add version 1.0.0.2

bucket/mameui.json
=> mameui: Add version nightly

bucket/hedgewars.json
Just not much more than the commit message says.
=> hedgewars: Update to version 1.0.0

bucket/dwarf-fortress.json
Persist data is done allowing saves, pictures, mods, and preferences.
Still trying to get CMD usage to work
*Maintainer edit: This closes #210.*
=> dwarf-fortress: Persist the `data` folder

bucket/openhv.json
An Open Source 90s Pixelart Science-Fiction Real Time Strategy game with Multiplayer (LAN and internet) support, competent skirmish AI as well as an integrated map editor.  All the assets are licensed under Open Source compliant terms. It is very easy to mod.
In 1993 a game called Hard Vacuum was in development. Heavily inspired by Dune 2, the father of the modern RTS, it had ambitious goals, but it was never released to the public. Decades later the pixel art was released under a free license. The starting point for this project.
If you like classic Westwood Studios style real time strategy games be sure to check out OpenRA upon which this game is built.
https://lostgarden.home.blog/2005/03/27/game-post-mortem-hard-vacuum/
- please check license, source says it's GPL-3.0 for code, but I …
=> Add OpenHV version 20210321

bucket/openmw-nightly.json
Should correct #259.
I had to change the entire autoupdate to work on jobs and not commit. It should work, but I will check in some days if there are no issues.
=> openmw-nightly: Fix autoupdate

bucket/xenia.json
Add `content` and `cache` to persist dir setup script.
=> xenia: fix persistence

bucket/mcedit2.json
This will prevent errors in future *autoupdate*s.
I did not check thoroughly in the original PR. Sorry.
=> mcedit2: Fix autoupdate

bucket/mednaffe.json
Forgot a quotation mark and closing brace
=> mednaffe: script fix

bucket/mgba-dev.json
Fix for #290 Its a little hacky but works.
=> mgba-dev: Fix for #290

bucket/project64.json
*Maintainer edit: This closes https://github.com/Calinou/scoop-games/issues/292.*
=> project64: Fix hash

bucket/osulazer.json
=> osulazer: Fix `extract_dir`

bucket/snes9x.json
=> snes9x: Update license, persist more files

bucket/sil.json
Autoupdate now works
(exclude the name of the manual).
=> sil: Fix autoupdate, persist more files

bucket/xonotic.json
=> xonotic: Add autoupdate

bucket/urbanterror.json
=> urbanterror: Add autoupdate, update website URL

bucket/redeclipse.json
=> redeclipse: Add autoupdate

bucket/runebook.json
Maintenance has changed
Closes #333
=> runebook: Update to version 1.14.6, update URLs

bucket/demul.json
=> demul: Add version 07_280418

bucket/tic-80.json
=> tic-80: Update to version 0.90.1723, fix autoupdate

bucket/sw-exporter.json
=> sw-exporter: Update to version 0.0.45, fix autoupdate

bucket/stuntrally.json
=> stuntrally: Add autoupdate

bucket/ufoai.json
=> ufoai: Add autoupdate

bucket/vdrift.json
=> vdrift: Add autoupdate

bucket/supertuxkart.json
=> supertuxkart: Add autoupdate

bucket/srb2kart.json
=> srb2kart: Add autoupdate

bucket/spearmint.json
=> spearmint: Update to version 1.0.3, add autoupdate

bucket/uhexen2.json
=> uhexen2: Add autoupdate

bucket/sauerbraten.json
Since the name of the folder is appropriate, the update will succeed only when it matches the file name.
=> sauerbraten: Add autoupdate, change version name to use underscores

bucket/paintball2.json
=> paintball2: Update to version build043, add autoupdate

bucket/mesen-s.json
=> mesen-s: Fix installation

bucket/mesen.json
Remove unnecessary folders from persist,
Closes #359
=> mesen: Update persisted files, add autoupdate

bucket/melonds.json
Exclude bios and firmware from persist
Closes #361
=> melonds: Exclude BIOS and firmware from persist

bucket/mcservman.json
=> mcservman: Add autoupdate

bucket/katrain.json
=> katrain: Update to version 1.9.3, add autoupdate and persist

bucket/jim.json
=> jim: Update to version 0.9.9.9.9.9.9.5.3, add autoupdate

bucket/ivan.json
=> ivan: Update to version 058, fix autoupdate

bucket/iortcw.json
=> iortcw: Fix 64-bit installation

bucket/infraarcana.json
It was changed to the development version according to the manufacturer's recommendation.
=> infraarcana: Update to version 20211017-c078746a, add autoupdate

bucket/hedgewars.json
=> hedgewars: Add autoupdate

bucket/golly.json
=> golly: Add autoupdate

bucket/freedroidrpg.json
=> freedroidrpg: Update to version 1.0rc2, add autoupdate

bucket/freeorion.json
=> freeorion: Add version 0.4.10.2

bucket/freeorion-test.json
=> freeorion-test: Add version 2021-10-26.9fd3aaa

bucket/flycast.json
=> flycast: Persist more files, mark as 64-bit only

bucket/extremetuxracer.json
=> extremetuxracer: Add autoupdate

bucket/ecwolf.json
=> ecwolf: Add autoupdate

bucket/cemu.json
setting.xml is backed up.
Add a script.
Closes #349
Closes #350
Closes #351
=> cemu: Fix and improve persist

bucket/angband-dev.json
This is Angband pre-release version.
=> angband-dev: Add version 4.2.3-103-gc3a0624e8

bucket/assaultcube.json
=> assaultcube: Add autoupdate

bucket/brogue.json
Modify Download URL.
Remove autoupdate because development is done.
Closes #199
Closes #332
=> brogue: Fix installation, remove autoupdate

bucket/odamex.json
=> odamex: Update to version 0.9.5, add autoupdate

bucket/openmsx.json
=> openmsx: Add version 17.0

bucket/openmsx-dev.json
=> openmsx-dev: Add version 17.0-209-g3bd64e2ab

bucket/prboom-plus.json
=> prboom-plus: Update to version 2.6.1, add autoupdate

bucket/endless-sky.json
=> endless-sky: Add shortcut, persist data

bucket/doomsday.json
=> doomsday: Update to version 2.3.1, add autoupdate

bucket/corporateclash.json
=> corporateclash: Update to version 1.2.1, add autoupdate

bucket/cemuhook.json
=> cemuhook: Update to version 0.5.7.5, fix autoupdate

bucket/openmw.json
I removed the 32 bit architecture which is no longer supported and updated the manifest to 0.47.0.
=> openmw: Update to version 0.47.0

bucket/ps3-system-software.json
=> ps3-system-software: Fix autoupdate

bucket/nanoboyadvance.json
NanoBoyAdvance is a Game Boy Advance emulator focused on accuracy.
=> nanoboyadvance: Add version 1.4

bucket/flycast.json
Updates the manifest to v1.2.
Also updates the autoupdate section since the words have been thrown around and skips the V before the version.
=> flycast: Update to version 1.2

bucket/dxwrapper.json
DxWrapper let's you wrap DirectX APIs to fix compatibility issues with older games.
=> dxwrapper: Add version 1.0.6542.21

bucket/dxvk.json
A Vulkan-based translation layer for Direct3D 9/10/11.
=> dxvk: Add version 1.9.2

bucket/ares.json
Configure as Portable Version
Closes #452
=> ares: Add version 124

bucket/xebra.json
=> xebra: Add version 211031

bucket/ryujinx-dev.json
Fix #512 
Updated to use the new official release repo
=> ryujinx-dev: Update to version 1.1.9

bucket/scummvm.json
Credit goes to [hermanjustnu](https://github.com/hermanjustnu/scoop-emulators/blob/master/bucket/scummvm.json).
The manifest looks good out the gate.
=> scummvm: Add version 2.5.1

bucket/openmw-nightly.json
Corrected checkver because of change from Gitlab.
=> openmw-nightly: Fix checkver

bucket/xenia-canary.json
xenia_canary: Update to version 7b6cbc2
Closes #525
=> xenia-canary: Add version 7b6cbc2

bucket/xemu.json
=> xemu: Add version 0.6.2-75-g8919bae311

bucket/redream-nightly.json, bucket/redream.json, bucket/xenia-canary.json, bucket/xenia.json, bucket/yuzu-pineapple.json, bucket/yuzu.json
=> Fix various things in Redream, Xenia and Yuzu manifests

bucket/vkquake2.json
Added Persist.
Persist libraries are updated during automatic updates.
=> vkquake2: Add persist

bucket/blade-of-agony.json
Upgraded to the final version.
Added a script to download from a URL randomly generated by moddb.com.
Added Persist.
=> blade-of-agony: Update to version 3.1, use ModDB download, add persist

bucket/neverball.json
=> neverball: Add autoupdate

bucket/augmentinel.json
Install from zip file.
Closes #336
=> augmentinel: Update to version 1.5, add autoupdate, install from ZIP

bucket/yuzu-pineapple.json, bucket/yuzu.json
=> yuzu: Update license

bucket/assaultcube.json, bucket/assetstudio.json, bucket/freeciv.json, bucket/katrain.json, bucket/minutor.json, bucket/nethack.json, bucket/polymc.json, bucket/prboom-plus.json, bucket/q2pro.json, bucket/undertale-mod-tool.json, bucket/wesnoth.json, bucket/widelands.json, bucket/xemu.json, bucket/xenia-canary.json
closes #573 
xenia-canary: change to nightly
freeciv: fix checkver and url
xemu: fix checkver
assetstudio: fix download url
katrain: fix dl url
assualtcube: Update to version 1.3.0.1
q2pro: fixed, now nightly
undertale-mod-tool: fix dl url
minutor: fix dl url
=> Fixed freeciv, xenia-canary, xemu, and more

Scoop-Bucket.Tests.ps1, bin/auto-pr.ps1, bin/checkurls.ps1, bin/checkver.ps1, bin/formatjson.ps1, bin/missing-checkver.ps1, bin/test.ps1
=> bin: Fix formatjson and others erroring

bucket/bsnes.json
=> bsnes: Add version 115

.vscode/extensions.json, .vscode/settings.json, appveyor.yml, bucket/cemu.json, bucket/cemuhook.json, bucket/mednafen-dev.json, bucket/mednafen.json, bucket/mednaffe.json, bucket/melonds.json, bucket/mesen-s.json, bucket/mesen.json, bucket/mgba-dev.json, bucket/mgba.json, bucket/pcsx2-dev.json, bucket/pcsx2.json, bucket/ppsspp-dev.json, bucket/ppsspp.json, bucket/project64-dev.json, bucket/project64.json, bucket/redream-dev.json, bucket/redream.json, bucket/retroarch-nightly.json, bucket/retroarch.json, bucket/ryujinx.json, bucket/scummvm.json, bucket/snes9x-dev.json, bucket/visualboyadvance-m-nightly.json, bucket/visualboyadvance-m.json, bucket/yuzu-pineapple.json
=> appveyor: update scoop repo url, update poweshell 6 to current

README.md
=> Update copyright statements to 2022

bucket/fbneo.json
- Adjusts the manifest order according to the [contribution guidelines](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- Generalizes the contents of notes, which has the upside of making the sentences themselves read better as well.
=> fbneo: Adjust the manifest order and Notes

bucket/wiiscrubber.json
[x ] I have read the [Contributing Guide](../CONTRIBUTING.md).
- [x ] stable
=> wiiscrubber: Add version 1.4

bucket/polymc.json
Fixing the autoupdate of PolyMC since they're using github releases now :) 👍🏿
=> polymc: Fix autoupdate

.github/pull_request_template.md, bucket/cemu.json, bucket/visualboyadvance-m-nightly.json, bucket/visualboyadvance-m.json
> - [x] stable
> - [ ] beta
> - [x] dev/nightly/canary
> 
>   - [x] script pre-creates generated files listed in persist? (solves linking issue with generated files that need to be persisted)
> - [x] a short terse …
=> vba-m: set config for persists

bucket/cemu.json
cemu likes to delete and recreate the file if symlinked
=> cemu: Fix persist of `settings.xml`

bucket/unrealmodloader.json
> - [x] stable
> - [ ] beta
> - [x] a short terse description matching existing style.
> - [x] url to the release along with its sha256 hash
> - [x] passes `bin/checkver.ps1` and `bin/checkurls.ps1`
> - [x] tested install, checked persist, no errors.
> - [x] manifest is sorted to spec
> - [x] manifest follows spec: appname or appname-variant …
=> unrealmodloader: Add version 2.2.0

bucket/unrealmodloader.json
=> unrealmodloader: Add note for autoinjector tool 

bucket/demulshooter.json
This is a manual update to the latest version.
I'm not updating autoupdate since the author has made a simple typo with this release.
=> demulshooter: Update to version 10.5.0

bucket/l4d2modmanager.json
[l4d2modmanager](https://github.com/xavier-cai/L4D2ModManager) is a mod manager for the game Left 4 dead 2.
> - [x] stable
> - [ ] beta
> - [ ] autoupdate and checkver entry [](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate)
>   - [ ] a pre_install script creates runtime created files specified in persist (ensures …
=> l4d2modmanager: Add version 1.0.4

bucket/ferium.json
Update the description, homepage URL, and version tag for the Ferium application
=> ferium: Update to version 4.0.2, improve description

bucket/melonds.json
Closes #617 
The url scheme changed
=> melonds: Update to 0.9.4

bucket/rpcs3.json
Old method was essentially doing persistence manually on every install/upgrade
=> rpcs3: Fix persistence and disable built-in autoupdate

bucket/livesplit.json
> - [x] stable
> - [ ] beta
>   - [ ] a pre_install script creates runtime created files specified in persist (ensures symlinks properly get created)
> - [x] a short terse description matching …
=> livesplit: Add version 1.8.19

bucket/ferium.json
=> ferium: simplify autoupdate hash

bucket/doomrunner.json
Modern preset-oriented graphical launcher of ZDoom and derivatives
=> doomrunner: Add version 1.5.1

bucket/vita3k.json
- Suggest `vcredist`
- Updated some fields to match with Scoop guidelines
- Simplify `pre_install`
- Update version format to `<build>-<commit>` to match with the version displayed in vita3k:
=> vita3k: Update to version 2786-7ac13c3

.github/pull_request_template.md, CONTRIBUTING.md
Simplify PR template to match with the other official buckets.
=> Simplify PR template

bucket/xonotic.json
=> xonotic: Update to version 0.8.5

bucket/tf2-hud-editor.json
=> tf2-hud-editor: Add version 2.5

bucket/heroic-games-launcher.json
=> heroic-games-launcher: Add version 2.4.3

bucket/clonehero.json
=> clonehero: Add version 0.23.2.2

bucket/pegasus.json
=> pegasus: Add version alpha16-42-g996720eb

bucket/pegasus.json
=> pegasus: Fix notes, add `pre_install`

bucket/rimpy.json
=> rimpy: Add 1.2.5.21

bucket/prismlauncher-qt5.json, bucket/prismlauncher.json
since 5.1, Windows is 64 bit and Windows-Legacy is 32 bit
=> prismlauncher: Declare architecture

CONTRIBUTING.md, README.md
=> Update outdated information in the README

.github/workflows/ci.yml
To match with other official buckets
=> Update `actions/checkout` version

bucket/duckstation.json
Closes https://github.com/Calinou/scoop-games/issues/751
=> duckstation: Fix installation

bucket/ares.json
=> ares: Update website URL

bucket/duckstation-preview.json
=> duckstation-preview: Add version 20221208-g1905ce3

bucket/steam-achievement-manager.json
=> steam-achievement-manager: Add version 7.0.25

bucket/zandronum.json
Added `checkver`, `autoupdate`, `persist`, fix `pre_install`, and add `pre_uninstall`
Closes #748
=> zandronum: Update to 3.1

bucket/zandronum.json
@ZzZombo suggested I add his fixes to the manifest to better accomidate Scoop.
Relates to https://github.com/Calinou/scoop-games/pull/768#issuecomment-1362365343
=> zandronum: Add suggested fixes

bucket/cambridge.json
=> cambridge: Add version 0.3

bucket/toontownrewritten.json
=> toontownrewritten: Update to version 1.5.2.0

bucket/bloxstrap.json
=> bloxstrap: Add version 1.6.1

bucket/texmod.json, bucket/umod.json
=> texmod, umod: Add version 2_r53

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/hash-error.yml, .github/ISSUE_TEMPLATE/package-request.yml
Copied from the official buckets:
=> Add issue templates

bucket/duelyst.json
This PR adds Duelyst open source implementation. 
Duelyst is the ultimate tactical card game with lightning fast matches. Compete in head-to-head matches where every move requires thoughtful decision-making and strategic positioning. Assemble your deck from cards across 6 unique factions and test your mettle against other players!
Here's announcement: https://youtu.be/h3Cuz6d_7x0
=> duelyst: Add version 1.97.12

bucket/racelab.json
Racelab provides overlays for racing games. The package `actools` is also in this bucket, which is another application meant to compliment racing games.
I've been running this manifest in my scoop bucket for a bit: https://github.com/scowalt/scoop-apps
=> racelab: Add version 3.5.0

bucket/heroic-games-launcher.json
=> heroic-games-launcher: Fix `url`, remove `bin`, and fix `autoupdate`

bucket/tf2-hud-editor.json
=> tf2-hud-editor: Fix `extract_dir` following upstream changes

bucket/runelite.json
Adds a manifest for the Runelite launcher, which is an open source client for Old School Runescape.
=> runelite: Add version 2.6.1

bucket/raine.json
Also reorders Autoupdate section to have the same order as the installation section.
=> raine: Update to version 0.95

bucket/openloco.json
Add OpenLoco - Open source re-implementation of Chris Sawyer's Locomotion.
=> openloco: Add version 23.02

bucket/dgvoodoo2.json
=> dgvoodoo2@2.8: Fix hash

bucket/itch.json
=> itch: Fix `checkver` to be more accurate

bucket/doom-retro.json
=> doom-retro@4.9: Fix hash

bucket/rvgl-launcher.json
Closes https://github.com/ScoopInstaller/Extras/issues/10298
=> rvgl-launcher: Add version 0.1.22.314a1

bucket/wemod.json
=> wemod: Add version 8.6.0

bucket/wemod.json
Relates to #886
fix: checkver regex
=> wemod: Update to version 8.7.0

bucket/rare.json
=> Rare: Add version 1.10.1

bucket/rbxfpsunlocker.json
=> rbxfpsunlocker@5.0: Add hotfix

bucket/pyfa.json
=> Add: pyfa 2.52.0

bucket/goggalaxy.json
=> Add: GOG Galaxy 2.0.62.26

bucket/steam-art-manager.json
=> Add: steam-art-manager

bucket/xenia-canary.json
I am using the update method from this manifest: https://github.com/hermanjustnu/scoop-emulators/blob/master/bucket/xenia-canary.json
Closes https://github.com/Calinou/scoop-games/issues/717
=> xenia-canary: Add version 20221205172514-747fb42

bucket/xmoto.json
Closes #444 as it rebases and updates it
=> xmoto: update to 0.6.2

bucket/assaultcube.json
=> assaultcube: update to 1.3.0.2

bucket/freeorion.json
Closes #XXXX
Relates to #334 and #336
=> freeorion: update to 0.5

bucket/freeorion-test.json
=> freeorion-test: add full-screen option

bucket/yquake2.json
=> yquake2: persist libraries and music

bucket/undertale-mod-tool.json
Closes #437 and closes #810 and closes #808
=> undertale-mod-tool: update to 0.5.1.0 and fix shim

bucket/armagetronad.json
Closes #368 as it updates and rebases it
=> armagetronad: update to 0.2.9.1.0 and add autoupdate

bucket/rvgl.json
=> rvgl: add hash checking and persists

bucket/rvgl.json
Reverts Calinou/scoop-games#934
=> Revert "rvgl: add hash checking and persists"

bucket/ppsspp.json
PPSSPP seems to have changed their website, breaking autoupdate.
=> ppsspp: update to 1.15.3 stable

bucket/simutrans.json
=> simutrans: update to version 123.0.1

bucket/goggalaxy.json
=> goggalaxy: fix install

bucket/stuntrally.json
=> stuntrally: update to 2.7

bucket/enigma.json
=> enigma: update to 1.30

bucket/pychess.json
=> pychess: update to 1.0.4

bucket/ironwail.json
=> ironwail: fix shim

bucket/crispy-doom.json
=> crispy-doom: update to 6.0

bucket/freedroidrpg.json
=> freedroidrpg: update to 1.0

bucket/visualboyadvance-m.json
=> visualboyadvance-m: update to 2.1.5

bucket/wesnoth.json
Closes #XXXX
Relates to #334 #336 https://github.com/ScoopInstaller/Main/issues/773
=> wesnoth: update to 1.16.9

bucket/bgb.json
=> bgb: persist ini and screenshot folder

bucket/wyrmsun.json
Closes #442 as it updates and rebases it
=> wyrmsun: update to 5.3.6

bucket/clonehero.json
=> clonehero: update to 1.0.0.4080

bucket/speed-dreams.json
Closes #468 as it rebases and updates it
=> speed-dreams: update to 2.3.0-r8786

bucket/cataclysm-dda-tiles.json
Closes #375 as it updates and rebases it
=> cataclysm-dda-tiles: update to 0.G

bucket/unciv.json
=> unciv: update to 4.6.12 and remove deprecated 32 bit

bucket/evemon.json
=> evemon: add version 4.2.2

bucket/ffxivquicklauncher.json, bucket/xivlauncher.json
=> xivlauncher: add version 6.3.4

bucket/modbreeze.json
Added the `modbreeze` package version `0.4.0`.
Modbreeze is a fast and easy to use mod manager for Minecraft written in Rust that allows easy sharing of modpacks with your friends using TOML.
=> modbreeze: add version 0.4.0

bucket/jeveassets.json
=> jeveassets: add version 7.6.1

bucket/evemaptool.json
=> evemaptool: add version 1.20

bucket/applewin.json
=> applewin: add version 1.30.14.1

bucket/idlemaster-extended.json
=> idlemaster-extended: add version 1.10.0

bucket/advanced-combat-tracker.json
=> advanced-combat-tracker: add version 3.6.2.279

bucket/fheroes2.json
fheroes2 is a recreation of the Heroes of Might and Magic II game engine.
=> fheroes2: Add version 1.0.4

twitchdropsminer.json
=> twitchdropsminer: add version 15

bucket/beebem.json
=> beebem: add version 4.19

bucket/naev.json
=> naev: add 0.10.5

bucket/bloxstrap.json
=> bloxstrap: updated URL (version 2.4.0)

bucket/scummvm.json
Upstream changed the folder structure inside the `zip` file.
=> scummvm@2.7.1: Remove extract_dir

bucket/dgvoodoo2.json
- Closes #1029
Confirmed by doing another manual download.
=> dgvoodoo2@2.81.3: Fix hash

bucket/prismlauncher-qt5.json, bucket/prismlauncher.json
=> prismlauncher/prismlauncher-qt5@7.1: Fix crash at launch

bucket/doom-retro.json
=> doom-retro@5.0.3: Fix hashes

bucket/rbxfpsunlocker.json
Package "rbxfpsunlocker" has been updated to version v5.1 by the developer.
=> rbxfpsunlocker: Updated version v5.0 to v5.1

bucket/mudlet.json
> Mudlet is a platform for gaming and enhancing game-play primarily with MUDs.
— https://www.mudlet.org/
No persistent folder required. User data is stored in `%userprofile%\.config\mudlet`
=> mudlet: Add 4.17.2

bucket/cataclysm-dda-tiles-experimental.json
Remove the outdated 32 version.
Fix checkver
=> cataclysm-dda-tiles-experimental@2023-12-15-2138: fix manifest

bucket/sokoban.json
Add sokoban.json
https://github.com/ShenMian/sokoban-rs
=> Add sokoban.json

bucket/tmaze.json
Closes [#1084](https://github.com/Calinou/scoop-games/issues/1084)
=> ADD: tmaze

bucket/chiaki4deck.json
=> Add chiaki4deck

bucket/steam-achievement-manager-syntaxtm.json
The official release of Steam Achievement Manager is outdated and unmaintained. This fork is up-to-date and actively updates. I would consider replacing, but it's still WIP and resets the versioning.
I would consider dropping this to the Extras bucket, but the original SAM is on here, so...
=> syntax-tm's Steam Achievement Manager: Add version 0.2.0

bucket/prismlauncher-qt5.json, bucket/prismlauncher.json
These are for sort of user theme files:
- [catpacks](https://prismlauncher.org/wiki/getting-started/catpacks/)
- [iconpacks](https://prismlauncher.org/wiki/getting-started/change-themes/#icons-pack)
=> prismlauncher: Persist catpacks and iconthemes

bucket/battlenet.json
I referenced the shortcut that's created when installing the app through its installer.
=> battlenet: Add shortcut

bucket/sudachi.json
Adds sudachi, a continuation of the yuzu emulator project. Compared to suyu, this project actually attempts to advance emulation code and has already made (minor) progress on making newer games work.
Relates to https://github.com/Calinou/scoop-games/issues/1100 and https://github.com/Calinou/scoop-games/issues/1101
=> Sudachi: add version v7715077

bucket/shipwright.json
Ship of Harikinian is a PC Port of The Legend of Zelda: Ocarina of Time.
=> Shipwright: Add Ship of Harkinian

bucket/ff-logs-uploader.json
Created a new ff-logs-uploader.json for Scoop games bucket with auto-updating
=> ff-logs-uploader: Add initial version 8.3.20

bucket/chiaki4deck.json
=> Use VC build of chiaki4deck due to upstream issues

bucket/scummvm.json
=> scummvm: fix shortcut creation

bucket/dwarf-fortress.json
=> Change dwarf fortress autoupdate url to use $underscoreVersion

bucket/tic-80.json
=> tic-80: add shim

bucket/tmaze.json
Author of this game changed names of files and added 32bit version.
=> Tmaze: file names changed

bucket/dwarf-fortress.json
=> dwarf-fortress@50.12 fix persist folders

bucket/demulshooter.json
Downloaded manually as well, resulting in the same hash as committed.
=> demulshooter@12.2: Fix hash

bucket/undertale-mod-tool.json
=> undertale-mod-tool: remove extract dir as there is no longer a subfolder

bucket/collapse-launcher.json
Closes https://github.com/Calinou/scoop-games/issues/1078
=> collapse-launcher: Add version 1.73.8

bucket/lime3ds.json
Up-to-date and maintained fork of Citra. File mostly copied off the latest revision of citra.json.
Closes https://github.com/Calinou/scoop-games/issues/1132, https://github.com/Calinou/scoop-games/pull/1049 (not sure why was it open)
Relates to https://github.com/Calinou/scoop-games/issues/1100
=> Lime3DS: Add version 2114.1

bucket/project64.json
Not sure why it broke, how do I check autoupdate properly?
Closes https://github.com/Calinou/scoop-games/issues/1098
=> project64: Fix URL

bucket/mudlet.json
Closes https://github.com/Calinou/scoop-games/issues/1153
=> mudlet: Fix URL

bucket/wii-backup-manager.json
Closes https://github.com/Calinou/scoop-games/issues/1097
=> wii-backup-manager: Add version 0.4.6

bucket/opentyrian2000.json
Add manifest for OpenTyrian2000
=> Add: OpenTyrian2000

bucket/daggerfallunity.json
Introduction of Daggerfall Unity version 1.1.1
Closes #1178
=> daggerfallunity: Add version 1.1.1

bucket/sudachi.json
=> sudachi: Fix an unpaired bracket in pre_install

bucket/cnc-ddraw.json
Confirmed by multiple downloads.
=> cnc-ddraw@6.7.0.0: Fix hash

bucket/resolute.json
=> resolute: Add version 0.8.3

bucket/rimsort.json
=> RimSort: add 1.0.9

bucket/billy-frontier.json, bucket/bugdom-2.json, bucket/bugdom.json, bucket/cro-mag-rally.json, bucket/mighty-mike.json, bucket/nanosaur-2.json, bucket/nanosaur.json, bucket/otto-matic.json
---
This is a collection of games originally made by Pangea Software and officially ported by [jorio](https://github.com/jorio) to work on modern OSes.
=> Add Pangea Software Ported Games

bucket/playit.json
=> Add playit version 0.15.12

bucket/chunker-cli.json
=> chunker-cli: Add version 1.0.0

bucket/chunker.json
=> chunker: Add version 1.0.0

bucket/bedrock-launcher.json
An unofficial Minecraft for Windows launcher that enables similar features from the Minecraft Java Edition Launcher.
=> bedrock-launcher: Add version 2024.8.18.21

bucket/sudachi.json
Move homepage, checkvar and autoupdate to sudachi new home https://sudachi.emuplace.app/
Closes #1213
=> sudachi: Fix homepage, url and autoupdate

bucket/flashpoint.json
Closes [#1216](https://github.com/Calinou/scoop-games/issues/1216)
=> Flashpoint: Add version 13

bucket/megaanticheat.json
Relates to #[1220](https://github.com/Calinou/scoop-games/pull/1220)
_Originally posted by @amorphobia in https://github.com/Calinou/scoop-games/pull/1220#pullrequestreview-2276282626_
=> megaanticheat: fix notes part

bucket/chunker-cli.json, bucket/chunker.json
=> Fix chunker and chunker-cli

bucket/sudachi.json
=> Update sudachi.json with GitHub releases

bucket/fmodel.json
=> fmodel: Add version 4.4.3.6

bucket/shatteredpixeldungeon.json
=> shatteredpixeldungeon: add version 2.0.2

bucket/lime3ds.json
=> lime3ds@2119.1: Update URLs to point to archive

bucket/ryujinx.json
Ryujinx official repo no longer available. But there is an active fork with QoL updates. Scoop edited based on https://github.com/borger/scoop-emulators/blob/master/bucket/ryujinx.json
=> Update Ryujinx with active Fork

bucket/openrct2.json
=> Fix openrct2 autoupdate url

bucket/pcsx2-dev.json, bucket/pcsx2.json
Duplicate of #1259 and #1234 but with the requested changes. Those PRs seemed to have stalled so I decided to make my own.
Also closes #1233.
=> pcsx2, pcsx2-dev: fix autoupdate and persist

bucket/epic-games-launcher.json
=> epic-games-launcher: Use `head` & properly parse query params

bucket/melonds.json
fixed both outdated autoupdate and version URLs
=> melonds: fix autoupdate URL, update to 1.0rc

bucket/uabea.json
=> uabea: Add version 8

bucket/cxbx-reloaded.json, bucket/ppsspp-dev.json
=> fix cxbx-reloaded

bucket/retroarch-nightly.json
Closes https://github.com/Calinou/scoop-games/issues/1269
=> retroarch-nightly: add and fixes persistent folders

bucket/tf2classic.json
Closes https://github.com/Calinou/scoop-games/issues/1317
=> Tf2classic: repair checkver

bucket/flashpoint.json
=> Flashpoint: repair extraction and shortcut

bucket/doukutsu-rs.json
Open source Cave Story implementation, requires the game assets in data/
=> Add doukutsu-rs

bucket/sameboy.json
=> Fix removal of .exe file in sameboy package

bucket/goggalaxy.json
=> goggalaxy: Fix autoupdate

bucket/r2modman.json
This PR does the following:
- Updates description to match upstream
- Modifies licence to include url
- Changes download url to save file as an archive
- Adds a pre_install script to correctly extract the app out of said archive
Closes #1378
=> r2modman: Add pre_install script to extract app

bucket/maa.json
=> maa: Add version 5.15.2

bucket/dolphin.json
Update version and fix checkver.
=> dolphin: update to version 2503a

bucket/undertale-mod-tool.json
Updated the version and the actual main repository with the proper zip name, changed in the last two versions. Removed persistance config as its not working anymore
Closes #XXXX
=> undertale-mod-tool@0.8.0.0: Update version

bucket/asset-ripper.json
=> asset-ripper: Add version 1.2.2

bucket/sak.json
- `sak`: Add version `0.7.14`.
Closes #1388
=> sak: Add version 0.7.14

bucket/gdsdecomp.json
=> feat: add gdsdecomp

bucket/maa.json
=> maa@5.16.3: resolve conflicts with maa-cli

bucket/sak.json
- `SAK`: Edit notes. Replace `$env:SCOOP\\app\\sak\\current\\` with `$dir`.
=> sak: update notes

bucket/infraarcana.json, bucket/lime3ds.json, bucket/openmw-nightly.json, bucket/rpcs3.json, bucket/ryujinx-canary.json, bucket/tf2classic.json
- `lime3ds@2119.1`: Update url (from [reddit discussion](https://www.reddit.com/r/Roms/comments/1gv7rdx/help_im_trying_to_download_lime3ds_but_in_the/)), remove chever, remove autoupdate (since [it was archived](https://github.com/Lime3DS/lime3ds-archive/releases)).
- `infraarcana@23.0.0`: Fix installation.
- `tf2classic@2.2.2`: Remove post_install & pre_uninstall, add notes.
- `openmw-nightly`: Update to versioin 20250527-b0d38931, remove checkver, fix pre_install & post_install.
- `ryujinx-canary`: Update to version 1.3.62, fix checkver, fix autoupdate ([github repo migration](https://github.com/Ryubing/.github/commit/8a761a7682bd751841012b48f0e52f8beb9592ba)).
- `rpcs3@0.0.37-17987`: Fix autoupdate Hash Extraction.
Closes #1406
Relates to #1427
=> Fix manifests

bucket/mesen.json
Updates Mesen emulator to install the latest version
* Updated to Mesen 2
* Updated persist to work with the new file structure of mesen2
Closes #1441
=> Mesen@2.1.1: Update to mesen2

bucket/retro-rogue-collection.json
https://github.com/mikeyk730/Rogue-Collection
=> retro-rogue-collection: Add version 3.1.0

bucket/2ship2harkinian.json
=> 2ship2harkinian: Add version 1.1.2

bucket/hlae.json
=> feat: add HLAE to bucket

bucket/divamodmanager.json
Add Diva Mod Manger a mod manager for Hatsune Miku Project DIVA Mega Mix Plus to package list.
Closes #1524
- [x ] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).
=> Add Diva Mod Manger
