Calinou/scoop-games

- minecraft.json
I know it's not freeware, but actually you just need a licensed account to login, the launcher is actually available to everyone. So why couldn't we install via scoop?
Also it was requested: https://github.com/lukesampson/scoop-extras/issues/1373
> Add Minecraft Java Edition

- bucket/cataclysm-dda-tiles.json
- bucket/cataclysm-dda.json
This adds the open source roguelike Cataclysm: Dark Days Ahead curses and graphical versions.
I didn't include an autoupdate for these manifests because the version for releases are non-semver and scheduled for 6-month intervals (https://cataclysmdda.org/releases/)
> Add cataclysm-dda and cataclysm-dda-tiles.

- bucket/sw-exporter.json
Summoner's War Exporter is a Proxy which will capture your game data for Summoners War: Sky Arena, which may then be used to optimize runes or to manage monsters at online platforms such as https://swarfarm.com/.
Summoners War: Sky Arena, is a mobile turn-based strategy MMO game for Android and iOS.
See Also:
* https://swarfarm.com/
* https://github.com/Xzandro/sw-exporter
> Adds Summoner's War Exporter (current version: 0.0.25)

- bucket/0ad.json
**0 A.D.** ([homepage](https://play0ad.com/)) is a free, open-source game of ancient warfare.
Notes:
* This package installs the files by **running the installer**. Is this acceptable in the game bucket?
I know that in the general criteria of scoop, it is preferred to extract the files manually (rather than running the installer). The installer seems to be created by [this NSIS script](https://github.com/0ad/0ad/blob/master/source/tools/dist/0ad.nsi), but I could not find a way to extract it using 7zip/uniextract/innounp.
Therefore, I followed [this example from the nonportable bucket](https://github.com/oltolm/scoop-nonportable/blob/master/notepadplusplus-np.json) to create the manifest. The files will be installed under the scoop directory, and the shortcuts are created by the installer …
> 0ad: Add version 0.0.23b

- bucket/minecraft.json
Feedback is welcome. Here are the changes I made:
* `version` has been changed to `nightly` so that the hash doesn't have to be manually updated.
* `license.identifier` has been changed to `Proprietary` as the game is not free (although I suppose the *launcher* is free).
* Using the `current` junction no longer causes any issues, at least for me.
* Added `game` and `runtime` to persist. This is because I use `scoop update minecraft --force --no-cache` to update Minecraft, and redownloading `game` and `runtime` every time the launcher is updated is time-consuming.
:)
> Tweaks to minecraft.json

- bucket/pcsx2-dev.json
- bucket/pcsx2.json
For some reason $matchRandom wouldn't work with an & immediately after it, and I couldn't figure out how to escape it.
Fortunately the git revision appended to each build is always 10 characters long.
> Add PCSX2 and PCSX2-dev

- bucket/citra-canary.json
- bucket/citra.json
activates Citra's portable mode and migrates the user files from `%APPDATA%`
> Citra(-canary): add persistence

- bucket/bgb.json
- bucket/kega-fusion.json
- bucket/snes9x.json
close #75
This adds **persist** to `BGB`, `Kega-Fusion` and `Snes9x` packages.
* `BGB` already have its config file (bgb.ini) in the archive, therefore we don't need to create a new file in the **pre_install** section.
* I have tested the packages to make sure that `Kega-Fusion` and `Snes9x` works properly (will not crash) with an empty config file.
> Add persist for BGB, Kega-Fusion, Snes9x packages

- bucket/mesen.json
[Mesen](https://www.mesen.ca/): a high-accuracy NES and Famicom emulator and NSF player for Windows and Linux.
Github: https://github.com/SourMesen/Mesen
**Note:**
It's data can be saved into the user's document folder or application folder. If user download the zip, extract and execute the mesen.exe, will let user select which folder to save data. Here I force save data in the appdata by create a settings.xml file.
> mesen: Add version 0.9.8

- bucket/warzone2100.json
There was a problem with the Warzone2100 installation, since the release URL seem to have changed.
> Warzone2100 installation fixed

- bucket/mame.json
**MAME** ([homepage](http://mamedev.org)) is an arcade machine emulator.
Notes:
* The config files (`mame.ini`, `ui.ini` and `plugin.ini`) will be produced *in the current working directory* when running `mame.exe -createconfig`
> MAME: Add version 0.217

- bucket/enigma.json
close #78
**Enigma** ([homepage](https://www.nongnu.org/enigma/index.html)) is a puzzle game inspired by Oxyd on the Atari ST and Rock'n'Roll on the Amiga. The object of the game is to find uncover pairs of identically colored Oxyd stones.
Notes:
* **license**: Enigma is both licensed as `GPL 2.0 (or later)` and `LGPL 2.1 (or later)`. I seperate them using `|` following the example on [Scoop's wiki page](https://github.com/lukesampson/scoop/wiki/App-Manifests).
* **persist** is not needed because *Enigma* stores its user settings (and save data) under `$Env:AppData\Enigma`.
> Enigma: Add version 1.21

- bucket/openra.json
* **OpenRA** now provides both 32-bit and 64-bit binaries, and changed the file name pattern. Therefore *the Excavator* cannot update the package automatically. This fixes the issue.
* OpenRA stores its user settings in `$Env:UserProfile\Documents\OpenRA`. (Therefore *persist* is not needed for this package)
> OpenRA: Update to version 20191117 (manually)

- bucket/gzdoom.json
- bucket/lzdoom.json
**gzdoom** and **lzdoom** has changed their file name pattern. Therefore the packages cannot be automatically updated by the Excavator. This fixes the issue.
> gzdoom, lzdoom: Update manually

- bucket/nethack.json
**nethack** has changed their file name pattern. Therefore the package cannot be automatically updated by the Excavator. This fixes the issue.
I modified the manifest to download file from the Github repo instead of `nethack.org` because I cannot find a proper way to parse the pages to get the correct URL from `nethack.org`. 
(See https://www.nethack.org/common/index.html for details)
> nethack: Update to version 3.6.4 (manually)

- bucket/sw-exporter.json
**Summoner's War Exporter** has changed their file name pattern.  Therefore the package cannot be automatically updated by the *Excavator*. This fixes the issue.
> sw-exporter: Update to version 0.0.31 (manually)

- bucket/lf2.json
**Little Fighter 2** (often abbreviated as **LF2**) is a free fighting game that is well-known in the Chinese-speaking region.  ([homepage](http://www.lf2.net/)) ([Wikipedia](https://en.wikipedia.org/wiki/Little_Fighter_2))
Notes:
* *checkver/autoupdate* is not needed because **LF2** has not been updated since 2009.
* The installer from the official source cannot be properly extracted. Also the silent switch (`/S`) causes error for some reason. Therefore I use a **third-party source** ([azo freeware](https://www.azofreeware.com/2011/12/little-fighter-20a.html)) instead. Is this acceptable?
> lf2: Add version 2.0a

- bucket/openttd.json
When the installation files of openttd were updated the version number itself was forgotten.
> Fix version number for openttd

- bucket/gzdoom.json
This PR adds persistence for the GZDoom portable config file. The portable config file is documented [here](https://zdoom.org/wiki/Configuration_file) for ZDoom. GZDoom automatically detects the presence of `gzdoom_portable.ini` and uses it over the default config file (`gzdoom-<user>.ini`).
> gzdoom: Persist config file

- bucket/gzdoom.json
- bucket/zdl.json
[ZDL](https://zdoom.org/wiki/ZDL) is the [ZDoom-recommended](https://zdoom.org/downloads#Support) (see also [here](https://zdoom.org/wiki/Frontend)) frontend/launcher for ZDoom engines.
This manifest installs the most up-to-date ZDL fork by lcferrum available [here](https://github.com/lcferrum/qzdl).
The fork stores its configuration in `AppData\Roaming\Vectec Software\qZDL.ini`, so no persistence is necessary.
> zdl: Add version 3-1.1

- bucket/ps3-system-software.json
- bucket/rpcs3-dev.json
Also added as a suggestion to rpcs3-dev.
This does not automatically set RPCS3 up to use the firmware.
You still have to install it through the interface.  This
just downloads it for you and should notify you via a package
upgrade when a new version is available.
> ps3-system-software: Add version 4.86

- bucket/vkquake.json
[vkQuake](https://github.com/Novum/vkQuake) is a Quake 1 port based on QuakeSpasm that uses the Vulkan graphics API for rendering.
I copied the QuakeSpasm manifest and made some basic additions for `checkver` and `autoupdate`. I also added a note from the vkQuake repo about needing the MSVC 2019 redists installed.
> vkquake: Add version 1.04.1

- bucket/openmw-nightly.json
The nightly version of OpenMW has a new hosting system which therefore broke the autoupdate. The manifest has been updated with the relevant information.
> openmw-nightly: Fix URLs and checkver following migration

- bucket/rpcs3-dev.json
I'm dumb, I thought something was wrong with the excavator but I went and looked at the release page today, they just bumped the base version from 0.0.9 to 0.0.10 and for some reason I didn't account for that in the original regex.  I didn't bother manually bumping the version but it should get picked up on the next excavator run.
> rpcs3-dev: Allow for multiple digits in version

- bucket/openmw-nightly.json
It seems that Scoop doesn't always update automatically this package even though the manifest version has changed. I suspect that is because the versioning scheme was only the commit hash and therefore was not 'incremental'.
I changed it with the versioning scheme of [ffmpeg-nightly](https://github.com/ScoopInstaller/Main/blob/master/bucket/ffmpeg-nightly.json) which seems to work correctly. It is now `YearMonthDay-commit`. I also think that having the date information is helpful for a nightly package.
> openmw-nightly: Change versioning scheme

- bucket/vkquake.json
* Add command-line shim
* Remove -game argument from default shortcut (makes shareware unusable)
* Use suggest instead of depends for vcredist
A note regarding the `-game id1` removal: That argument causes an error when using the shareware version of Quake (`id1\PAK0.PAK` without `id1\PAK1.PAK`):
Additionally, vkQuake (like QuakeSpasm) selects `id1` as the game by default without that argument.
Regarding the use of `suggest` instead of `depends` for the vcredist, this approach seems to be the best practice in other manifests such as [pcsx2](https://github.com/Calinou/scoop-games/blob/1f5a1eeb3ec8634ad2942942cf69b3f2bef09be4/bucket/pcsx2.json) and [several main bucket packages](https://github.com/ScoopInstaller/Main/search?p=1&q=vcredist&unscoped_q=vcredist).
> vkquake: Implement various manifest improvements

- bucket/quakespasm.json
* Add checkver and autoupdate
* Add command-line shim
* Remove `-game` argument from default shortcut (makes shareware unusable)
A note regarding the `-game id1` removal: That argument causes an error when using the shareware version of Quake (`id1\PAK0.PAK` without `id1\PAK1.PAK`):
Additionally, QuakeSpasm selects `id1` as the game by default without that argument.
> quakespasm: Implement various manifest improvements

- bucket/actools.json
> Alternative launcher for Assetto Corsa named Content Manager, and some utils as well
https://github.com/gro-ove/actools
> actools: Add version 0.8.2123.36398

- bucket/blockbench.json
[Blockbench](https://blockbench.net/) is a handy tool for creating models and textures for games like Minecraft.
> blockbench: Add version 3.6.5

- bucket/legendary.json
close #124 
**Legendary** ([Github repo](https://github.com/derrod/legendary)) is a free, open-source Epic Games Launcher alternative.
Notes:
* Legendary is a command line tool. Therefore **shortcuts** is not needed.
* **persist** is not needed because Legendary stores its config file at `$Env:UserProfile/.config/legendary/config.ini`.
* **Avira antivirus** reports that `legendary.exe` contains virus. I am not sure if other anti-virus software does so. (I have sent a [false positive feedback](https://www.avira.com/en/analysis/submit) to Avira)
> legendary: Add version 0.0.19

- bucket/openxcom.json
close #117
**OpenXcom** ([homepage](https://openxcom.org/)) ([Github repo](https://github.com/OpenXcom/OpenXcom)) is an open-source clone of "UFO: Enemy Unknown" ("X-COM: UFO Defense" in the USA release) and "X-COM: Terror From the Deep" videogames by Microprose.
Notes:
* **persist** is not needed because OpenXcom stores its config at `$Env:UserProfile\openxcom`.
* The **notes** section is written according to [the manual](https://github.com/OpenXcom/OpenXcom#installation).
> openxcom: Add version 2020_08_02_1732

- bucket/loot.json
close #125 
**LOOT** ([Github repo](https://github.com/loot/loot)) is a plugin load order optimisation tool for TES III: Morrowind, TES IV: Oblivion, TES V: Skyrim, TES V: Skyrim Special Edition, Skyrim VR, Fallout 3, Fallout: New Vegas, Fallout 4 and Fallout 4 VR.
Notes:
* **persist** is not needed since *LOOT* stores its config at `$Env:LocalAppData\LOOT`.
*  MSVC 2017 x86 redistributable is required for *LOOT* to run properly. (see: https://github.com/loot/loot/releases/tag/0.15.1). Also, Visual C++ 2015, 2017 and 2019 all share the same redistributable files. Therefore I put **vcredist 2019** in suggest. (see: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
> loot: Add version 0.15.1

- bucket/infraarcana.json
Add Infra arcana v20.0
The download url points to a build artifact on gitlab. From what I checked over several weeks, the url is permanent. The download page also directs to gitlab pipelines which eventually redirect the browser to the build artifact. I haven't been able to find a way to make scoop follow that url. 
In the meantime, this is a way to install Infra Arcana using scoop.
> Add Infra Arcana version 20.0

- bucket/assetstudio.json
This is my first Manifest, so let me know if you find any mistakes!
It has a checkver, but no autoupdate. because need a JobID and a BuildID to download the artifact from AppVeyor, which requires two http requests.
> Add AssetStudio 0.15.0

- bucket/katrain.json
KaTrain is a tool for analyzing and playing go with AI feedback from KataGo.
It is a very helpful software to play Go but also to get AI feedback on our games. More info on their [github](https://github.com/sanderland/katrain).
> katrain: Add version 1.7

- bucket/openmw-nightly.json
A fix once again for the new build system for openmw-nightly. The manifest was update to the latest version in the process.
> openmw-nightly: Fix manifest for new build system

- bucket/openmw-nightly.json
I realized that the manifest I made yesterday was only compatible with PowerShell Core, so I corrected it for Windows PowerShell and made it a little bit cleaner in the process. Sorry for the trouble.
> openmw-nightly: Fix for Windows PowerShell

- bucket/mgba-dev.json
It looks like at some point in time (or maybe I just missed it when I made it) mgba got a [builds page](https://mgba.io/builds/1/).    
Using this we can reliably get a build and avoid the hash mismatch issues.
> mgba-dev: return to normal versioning

- bucket/katrain.json
The version tags on Github were changed so I had to change the autoupdate URL.
> katrain: Fix autoupdate

- bucket/advanced-genie-editor.json
[Advanced Genie Editor](http://aok.heavengames.com/blacksmith/showfile.php?fileid=11002) is a data editor for Age of Empires I/II (including DE), Star Wars Galactic Battlegrounds and Clone Campaigns.
Notes:
* **Direct download link** is not available on the official website. Therefore, I use an alternative link. Is this acceptable?
* GPL 3.0 license is specified in the [official repo](https://github.com/Tapsa/AGE/blob/master/Copying.txt).
> advanced-genie-editor: Add version 2021.3.15

- bucket/raze.json
- Updated urls to match the new naming scheme; omitting the beta tag.
- This also makes the json update to the latest available version.
> raze: Update to version 1.0.1

- bucket/mameui.json
- Add description
- Persist folders that I believe to be the most appropriate; those that save things like settings, snapshots, nvram and similar, and not folders like roms and similar since these are often specified to custom directories anyway.
Sadly I can't persist the ini files in the root folder since these are created on the first startup of the software.
> mameui: Add description, persist folders

- bucket/amidst.json
Take 2 of #184, it keeps the `jar` version of amidst and so should work fine for everyone.
* adds amidst icon to start menu
* shows log output in batch window
* provides access to the amidst cli
I also formatted the file first with `formatjson.ps1`.
> Improve amidst.json

- bucket/assetstudio.json
They started using the github release again for the release, so autoupdate is now available.
> assetstudio: Update to version 0.15.47, add autoupdate

- bucket/dolphin-dev.json
- bucket/dolphin.json
Commit c63f4af broke dolphin portable mode by removing the `post_install` and instead creating `portable.txt` in `$persist_dir` during `pre_install`, which isn't correct.
Removed that line from `pre_install` and restored the removed `post_install`.
> dolphin: Fix portable mode broken by c63f4af

- bucket/openmw-nightly.json
Since my last fix, the autoupdate could trigger on failed build, which made the installation fail. I updated the regex to check for this.
> openmw-nightly: Update only if the build passed

- bucket/yquake2.json
Took another shot at it, turns out scoop has a built-in last match function. No need for regex non-sense.
This also updates yquake2 to 8.00
Closes #266
> yquake2: Update to version 8.00

- bucket/mame.json
This PR 
1. updates MAME to 0.232
2. Fixes persistence issues caused by scoop trying to persist before `-createconfig` finishes running
3. Prompts 32bit users to install 0.217, by running `scoop install` on an old version of the manifest
4. Removes auto update for 32bit
5. Closes #244
> mame: Overhaul

- bucket/mgba-dev.json
The comment lines will cause following error message when searching for any apps:
```
convertfrom-json : 无效的 JSON 基元: 。(invalid JSON primitive)
所在位置 C:\Users\xxx\scoop\apps\scoop\current\lib\manifest.ps1:10 字符: 45
+     Get-Content $path -raw -Encoding UTF8 | convertfrom-json -ea stop
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```
> Fix "invalid JSON primitive" error

- bucket/openmw-nightly.json
There seems to have been a change in the GitLab webpage so the regex had to be updated. Hopefully they don't change it too often.
> openmw-nightly: Fix checkver regex

- bucket/melonds.json
They added an underscore before 'x64' in the URL making autoupdate string invalid - hopefully this is the only thing they changed this release.
EDIT: check fail says this:
"The following 1 lines contain trailing whitespace: 
File: C:\projects\scoop-games\bucket\opdessertstorm.json, Line: 31"
Don't know where this comes from as it's nothing to do with this manifest.
> melonds: Update to version 0.9.3, fix autoupdate

- bucket/rpcs3-dev.json
There are some files and folders that aren't persisted for RPCS3:
| Folder | Explanation |
| - | - |
| `dev_flash` | Where the firmware is installed to. Persisting this avoids having to reinstall the firmware every updated. |
| `cache` | PPU modules can take quite bit of time to compile on first run of a game, persisting this allows cache from the previous version to work. |
| `config.yml` | The global emulator configuration. |
| `config` | Game-specific emulator configuration and controller configurations. |
| `games.yml` | The games visible in the game list when you start RPCS3. |
| `Icons` | Custom icon location. |
| `patches` | Downloaded game patches. |
To my knowledge, the built-in RPCS3 updater persists these files and folders, so scoop should too.
> Add RPCS3 persist files and folders.

- bucket/opdessertstorm.json
It was causing errors in CI:
```
Executing script C:\projects\scoop-games\Scoop-Bucket.Tests.ps1
Describing Style constraints for non-binary project files
[+] non-binary project files exist (202 found) 21ms
[+] files do not contain leading UTF-8 BOM 248ms
[+] files end with a newline 24ms
[+] file newlines are CRLF 164ms
[-] files have no lines containing trailing whitespace 85ms
RuntimeException: The following 1 lines contain trailing whitespace: 
File: C:\projects\scoop-games\bucket\opdessertstorm.json, Line: 31
at <ScriptBlock>, C:\projects\scoop\test\Import-File-Tests.ps1: line 123
[+] any leading whitespace consists only of spaces (excepting makefiles) 54ms
```
> opdessertstorm: Remove trailing whitespace

- bucket/rpcs3-dev.json
Overlooked this in the last PR (#310), scoop needs to create empty `config.yml` and `games.yml` persist files since they are not included in the RPCS3 default files.
Currently scoop creates  `config.yml` and `games.yml` as folders, which causes errors in RPCS3.
I used the same method as the cemu install script:
https://github.com/Calinou/scoop-games/blob/c3f650d568873c15a181611da28a750c7f2d5982/bucket/cemu.json#L20-L22
> rpcs3-dev: Create `.yml` files if they don't exist

- bucket/fbneo.json
Noticed that a "v" was missing before the version variable in the autoupdate URL - dunno if it actually mattered, but better safe than sorry.
> fbneo: Fix autoupdate

- bucket/flycast.json
Here's a manifest for the great emulator that's mainly for Sega Dreamcast, but also other platforms like Naomi and Atomiswave (also based on Sega's hardware).
What's missing is a link to its cfg file since this is created on first run - by the way, should files that are linked use a symbolic link or a hard link, and what's the reasoning behind that?
> flycast: Add version 1.1

- bucket/pcsx2-dev.json
For the last 5 versions of pcsx2-dev, the autoupdate regex was creating faulty URLs that fail to install.
For example, version 1.7.0-1806 has the following URL which downloads an incorrect file that is over a year old:
https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.7.0-dev-1806-gc1fea5bc1&platform=windows-x86#/dl.7z
The correct URL should be this one, which has an additional character in the commit hash:
https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.7.0-dev-1806-gc1fea5bc16&platform=windows-x86#/dl.7z
The solution is to adjust the regex to match one additional character for the commit hash.
> pcsx2-dev: Fix autoupdate commit regex

- bucket/duckstation.json
The version display was changed to build date and Commit number instead of nightly.
Fix simlink.
Closes #358
> duckstation: Fix installation, update to version 20210929-g13c5ee8

- bucket/cataclysm-dda-tiles-experimental.json
Add a persist folder.
Added due to missing license.
> cataclysm-dda-tiles-experimental: Update to 2021-10-30-0656, fix autoupdate, add persist

- bucket/cataclysm-dda.json
Rename shortcuts according to official site.
> cataclysm-dda: Add persist, rename shortcuts

- bucket/gdidrop.json
Tool to convert bin/cue files of Redump Dreamcast Images to gdi/bin/raw in order to run on Demul.
Closes #406
> gdidrop: Add version 1

- bucket/pathofbuilding-community.json
Rename bin to avoid conflicts.
Closes #336
> pathofbuilding-community: Update to version 2.11.0, rename `bin`, fix autoupdate

- bucket/nethack.json
After installation, a list of folders to store data is displayed.
It could theoretically be portable, but it's still a challenge.
> nethack: Show data paths after installation, fix autoupdate

- bucket/pcsx2-dev.json
Fixes #463 
PCSX2 no longer uses commits and `dev` in their development build versions and download URLs.
Since the build number became simpler, matching the `v` at the beginning will prevent some unintentional matches.
> pcsx2-dev: fix checkver regex and autoupdate url

- bucket/mgba.json
mGBA has had very simple versioning for a while.
This updates:
- The version to 0.9.3 which was released almost a day ago
- Checkver to simply use the github method
- Autoupdate to simply use the $version for matching
> mgba: Update to version 0.9.3, tweak checkver and autoupdate

- bucket/rbxfpsunlocker.json
changes checkver to `github` mode (as it should've been when this manifest was added, rbxfpsunlocker uses the releases system on github so we can benefit from it here) and changes the autoupdate urls to use github release urls instead of file IDs.
> rbxfpsunlocker: Update to version 4.4.1, fix autoupdate

- bucket/doom-retro.json
This fixes the persist of the config file, though it doesn't fix issue #315 since the controls still end up empty.
Therefore I've added this information in the notes to simply improve the situation a bit.
> doom-retro: Fix config file persist and add info to notes

- bucket/dgvoodoo2.json
Glide/DirectX implementation on D3D11/12. Play your old Glide and DirectX games even on the latest, modern versions of Windows.
> dgvoodoo2: Add version 2.77

- bucket/nanoboyadvance.json
Seems like the download has gotten a new hash making the download fail in Scoop, this corrects it to the latest one.
> nanoboyadvance: Fix hash

- bucket/rayman-control-panel.json
The purpose of this app is to unify existing game patches and fixes, as well as allowing extended configuration, for all the PC Rayman games.
> rayman-control-panel: Add version 12.1.0

- bucket/demulshooter.json
DemulShooter is an app that hooks into (mostly) emulators to allow users to play rail shooter games with up to 4 lightguns or HID devices.
> demulshooter: Add version 10.4.1

- bucket/xenia.json
According to the [Xenia download page](https://xenia.jp/download/), the new [GitHub releases repo](https://github.com/xenia-project/release-builds-windows/releases) is the place to get the latest releases.
> xenia: Update download location for 1.0.2555

- bucket/xenia.json
The persist list was incorrectly nested, which caused incorrect persisting after an update.
Specifically, it was causing the contents of all the files to be written to `portable.txt` and skipping the other files:
> xenia: Fix persist list

- bucket/doom-retro.json
The notes described the _doom dir as being under the DOOM Retro persist dir, which is not correct - so this corrects that.
It also inserts some space in the notes section to make it more readable and aesthetically pleasing.
> doom-retro: Improve the Notes section

- bucket/rpcs3-dev.json
fixes install when you don't have extras bucket added
> rpcs3: Suggest vcredist2019 instead of depending on it

- bucket/ppsspp-dev.json
The current link will be downloaded as .PHP file
> ppsspp-dev: Fix download link to be downloaded as 7z file

- bucket/q2pro.json
The version is indicated.
Added 64 bit version.
Automatic update enabled.
Libraries in the Persist folder are now updated on update.
The menu file is assumed to be customized, so it is excluded.
> q2pro: Add 64-bit and persist, use versioned release

- bucket/freeorion.json
Like the official installer, I have added a full-screen shortcut.
It was mentioned in the official wiki, so I decided it was necessary.
The bin was removed because it could not be executed normally outside of the installation folder.
> freeorion: Add fullscreen shortcut, remove broken `bin`

- bucket/spearmint.json
The description is detailed.
Add shortcut of OpenArena - The Mission Pack.
Added to suggest for easier access to openarena data.
Add Persist folders.
Add scripts to update the libraries in the Persist folders. This is required for all Quake 2/3 engines.
Additional information about data placement.
> spearmint: Add persist, add OpenArena mission pack shortcut, improve notes

- bucket/freedoom.json
The Manifest URL is now one for automatic updates while maintaining compatibility.
Added a script to install the same version of freedm.
Added manual shortcuts.
Add notes.
> freedoom: Update to version 0.12.1, add shortcut to manual, add notes

- bucket/ares.json
This should fix the extract dir by correcting it to the current version which is 127, and autoupdate by using cleanVersion.
> ares: Fix autoupdate and extract_dir

- bucket/fbneo-nightly.json
Emulator for arcade games and select consoles.
This is the nightly version.
> fbneo-nightly: Add the nightly version

- bucket/prboom-plus.json
The contents of [`prboom-plus-262-w32.zip`](https://github.com/coelckers/prboom-plus/releases/download/v2.6.2/prboom-plus-262-w32.zip) are wrapped in a folder.
> prboom-plus: Add `extract_dir`

- bucket/pcsx2-dev.json
The PCSX2 repository no longer provides 32 bit builds in their releases page: https://github.com/PCSX2/pcsx2/commit/8a4f1ef51a037d77d2746304d89bef6a325a790b
I believe the now broken `32bit` section in this manifest was preventing it from being autoupdated.
> pcsx2-dev: Remove 32-bit builds

- bucket/ferium.json
> - [x] stable
> - [ ] beta
>   - [ ] a pre_install script creates runtime created files specified in persist (ensures symlinks properly get created)
> - [x] a short terse description matching …
> ferium: Add version 3.27.0

- bucket/sixcells.json
[sixcells](https://github.com/oprypin/sixcells) is a level editor for [Hexcells](http://store.steampowered.com/app/304410/).
> - [x] stable
> - [ ] beta
>   - [ ] a pre_install script creates runtime created files specified in …
> sixcells: Add version 2.4.3

- bucket/spraygen.json
[spraygen](https://code.google.com/archive/p/spraygen/) is a .vtf spray generator for TF2/CSS/L4D/L4D2.
> - [x] stable
> - [ ] beta
>   - [ ] a pre_install script creates runtime created files specified in persist (ensures …
> spraygen: Add version 1.3.4

- bucket/l4d2modmanager.json
Fix persist with a pre_install script.
> - [x] stable
> - [ ] beta
> - [ ] properly named and capitalized shortcuts?
> - [ ] autoupdate and checkver entry [](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate)
>   - [x] a pre_install script creates runtime created files specified in persist (ensures symlinks properly get created)
> - [ ] license identifier and url
> - [ …
> l4d2modmanager: Fix persist with a pre_install script

- bucket/mame.json
The dummy URL added in https://github.com/Calinou/scoop-games/pull/269 for the 32-bit version of MAME is no longer online. This caused MAME's autoupdate to stop working, as reported in #612.
This PR changes it to the URL of the manifest JSON itself, which should stay valid for a long time. I also updated the manifest using `check-ver.ps1`.
> mame: Update to version 0.243, fix autoupdate

- bucket/rpcs3.json
RPCS3 overwrites files config.yml and games.yml when saving changes to them, which eliminates the hardlinks created by Scoop when installing the app. Without the hardlinks, these files do not persist when un/re-installing the app.
This PR works around the overwrite behavior by copying the .yml files to the persist directory before uninstall (`"uninstaller"` definition) and copying them back to the app during installation (`"pre_install"` definition). Because Scoop's default persist handling does not work for these files, I also removed them from the `"persist"` definition.
> rpcs3: Fix `config.yml` and `games.yml` not persisting between upgrades

- bucket/pcsx2-dev.json
PCSX2's development builds recently switched to a new Qt user interface and changed some of the files.
In this PR, I fix the the download URL/executable name and add new folders to the persist list.
> pcsx2-dev: Fix download URL for Qt release

- bucket/ferium.json
The previous PR, #628 was broken because the URLs still used my username (the repo has been transferred to `gorilla-devs`) and the 'architecture' file still used the old 4.0.1 release which has been deleted
> ferium: Fix version 4.0.2, update URLs

- bucket/ares.json
ares: Update to version 128 is not working. I guess you simply have to change line to "extract_dir": "ares-v128"
https://github.com/Calinou/scoop-games/issues/635
> Fix ares update

- bucket/openmw-nightly.json
A fix for openmw-nightly because the automatic builds were changed. I added a new check in the regex to only update if the commit was on the master branch.
> openmw-nightly: Fix checkver

- bucket/cemu.json
* Fixes #623
* In #598, `Setting.xml` is **manually** persisted, but it was not removed from the `persist` field, causing *Scoop* to persist twice and resulting in the file access error.
* Update suggestion of *VCRedist* ([the 2022 version is compatible with 2015-2022](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170))
> cemu: Fix persist

- bucket/vkquake.json
Many including myself consider the mod Arcane Dimensions for Quake as good, if not far greater than the base contents of the game.
This change persists the dir for the mod according to the instructions on its homepage; dir 'ad'.
> - [x] stable
>   - [x] a …
> vkquake: Persist for the Arcane Dimensions mod

- .gitattributes
This avoids **git conflicts** due to inconsistant line endings (`LF`/`CRLF`), which will sometimes cause users unable to update the bucket.
The fix was applied to all buckets under `ScoopInstaller` org.
related:
https://github.com/ScoopInstaller/Extras/issues/7546
https://github.com/ScoopInstaller/Extras/pull/8285
> (chore): Fix git conflicts with line endings

- bucket/yquake2-ref-vk.json
This is the vkQuake2 vulkan renderer library ported to Yamagi Quake II.
> - [x] stable
> - [ ] beta
>   - [x] a pre_install script creates runtime created files specified in persist (ensures symlinks properly get created)
> - [x] …
> yquake2-ref-vk: Add version 1.0.2

- bucket/raine.json
RAINE is an emulator for arcade games.
> - [x] stable
> - [ ] beta
>   - [x] a pre_install script creates runtime created files specified in persist (ensures symlinks properly get created)
> - …
> raine: Add version 0.93.5d

- bucket/raine.json
Noticed that the autoupdate section used HTTP instead of HTTPS.
> raine: Use HTTPS for autoupdate

- bucket/ironwail.json
A fork of the popular GLQuake descendant QuakeSpasm with a focus on high performance instead of maximum compatibility, with a few extra features sprinkled on top.
> - [x] stable
> - [ ] beta
>   - [x] a pre_install script creates …
> ironwail: Add version 0.6.0

- bucket/yquake2.json
This adds the suggestion to install the Vulkan renderer specifically made for Yamagi Quake II.
It's been ported from [vkQuake2](https://github.com/kondrak/vkQuake2) by the Yamagi team.
> - [x] stable
> - [ ] beta
>   - [x] a …
> yquake2: Add suggestion for yquake2-ref-vk

- bucket/game-backup-monitor.json
Game Backup Monitor: A tool which automatically backs up your saved games. 
https://github.com/MikeMaximus/gbm
https://mikemaximus.github.io/gbm-web/index.html
As a side note, the link to CONTRIBUTING.md doesn't work in the issue template. Same for the pre_install link.
> - [x] stable
> - [ ] beta
> - [ ] a [pre_install](https://github.com/ScoopInstaller/Scoop/wiki/Pre--and-Pos …
> game-backup-monitor: Add version 1.3.1

- bucket/kindandfair.json
This is a tool to mod the balance of retro Castlevania games, including randomization options.
> - [x] stable
> - [ ] beta
>   - [x] a pre_install script creates runtime created files specified in persist (ensures symlinks …
> kindandfair: Add version 1.5.2

- bucket/cnc-ddraw.json
cnc-ddraw can fix compatibility issues with older games, such as black screen, bad performance, crashes, or defective Alt+Tab. It does this by wrapping DirectDraw to renderers like GDI, OpenGL, or Direct3D 9.
> - [x] stable
> - [ ] beta
> - [x] [autoupdate and checkver entry](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate)
> - [x] a [pre_install](https://github.com/ScoopInstaller/Scoop/wiki/Pre-and-Post-install-and-un …
> cnc-ddraw: Add version 4.4.7.0

- bucket/ironwail.json
If the user has the Steam release installed, no additional setup is required and the source port can be started as-is.
This updates the `Notes` section with that information.
The corresponding information is found on the Github page for the project [here](https://github.com/andrei-drexler/ironwail#bonus-features).
> ironwail: Add info about automatic detection of the Steam release

- bucket/ares.json
This fixes the problem of "extract_dir is not being updated".
closes #637
closes #635
> ares: Fix autoupdate

- bucket/jazz2-resurrection.json
Jazz² Resurrection is an open-source reimplementation of the game Jazz Jackrabbit 2.
**Author's note regarding the mandatory repetition of the import-process upon every update:**
I successfully persisted the corresponding folders that end up containing all the game data, but upon simulating an update through Scoop, and then running Jazz² Resurrection again, it still ended up showing the message "Installation is corrupted!", hence why the `Notes` and `Persist` sections are as they are.
> - [x] stable
> - [ ] beta
> - [x] [autoupdate and checkver …
> jazz2-resurrection: Add version 0.7.3

- bucket/romsorter.json
Compress, or uncompress ROMs, detect duplicates, catalog, manage CHD and DAT data, sort for Everdrive, or create 1G1R sets - all with one app.
Closes #626
> - [x] stable
> - [ ] beta
> - [x] [autoupdate and checkver entry](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate)
> - [x] a [pre_install](https://github.com/ScoopInstaller/Scoop/wiki/Pre-and-Post-install-and-uninstall-scripts) script to auto-enable portable mode …
> romsorter: Add Release 5

- bucket/polymc.json
This reverts commit caae8a7bd9b54bb4ae39da696e26b0a9a0f6de66.
Useless, doesn't make any sense and people that used that package before that change won't see their instances anymore with that change in updates
> - [x] stable
> - [ ] beta
> - [ ] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).
> - [ ] properly named and capitalized shortcuts?
> - [ ] [autoupdate and checkver entry](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate)
> - [ ] a [pre_install](https://github.com/ScoopInstaller/Scoop/wiki/Pre-and-Post-install-and-un …
> Revert "polymc: Use portable version instead (#673)"

- bucket/vita3k.json
They are not config files. Persist `cache` folder instead.
> vita3k: Remove `lang`, `shaders-builtin`, `data` persist

- bucket/itch.json
> - [x] stable
> - [ ] beta
> - [x] [autoupdate and checkver entry](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate)
Data are saved to `$env:APPDATA` on default.
> - [ ] a [pre_install](https://github.com/ScoopInstaller/Scoop/wiki/Pre-and-Post-install-and-uninstall-scripts) script to auto-enable portable mode (if needed)?
>   - [ ] a pre_install script creates runtime created files specified in persist (ensures …
> itch: Add version 25.5.1

- bucket/gzdoom.json
This PR makes the Save and Screenshots persistent, to allow the user to keep their savegames and screenshots between installs. 
> - [x] stable
> - [ ] beta
> - [ ] properly named and capitalized shortcuts?
> - [ ] [autoupdate and checkver entry](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate)
> - [ ] a [pre_install](https://github.com/ScoopInstaller/Scoop/wiki/Pre-and-Post-install-and-uninstall-scripts) script to auto-enable portable mode (if needed)?
>   - [ ] a …
> gzdoom: Make Save and Screenshots persistent

- bucket/cnc-ddraw.json
Downloaded multiple times to confirm it doesn't change; would be indicative of malware activity.
> cnc-ddraw@4.4.9.0: Fix hash

- bucket/bsnes-mt.json
bsnes-mt is a fork of bsnes that adds video features like pixel-perfect, integer-ratio scaling, as well as the aspect ratio that corresponds to that of the SNES console.
> bsnes-mt: Add version 1.3.4

- bucket/cemu-dev.json
- bucket/cemu.json
The promised day hath come, cemu is now open source.     
Leaving this a draft for now, until the release structure straightens out. A stable and dev version are list on the main page, but the github releases show 2.0 as latest and 2.0-2 as latest dev.
> Cemu: Update and change release source

- bucket/opensupaplex.json
OpenSupaplex is a reverse engineered version of Supaplex for a lot of platforms including handhelds
> opensupaplex: Add version 7.1.2

- bucket/amulet-map-editor.json
Roll back to v0.10.2 (v0.10.3 does not exist).
Fix homepage URI.
Closes #730 and closes #731.
> amulet-map-editor: Fix version and website URL

- bucket/vkquake.json
The latest version deprecates the usage of an `extract dir` (based on the respective contents of the archives for each architecture).
Removing these from the manifest results in a successful install – this change reflects that.
> vkquake: Remove `extract_dir` to fix installation

- bucket/doom-retro.json
> doom-retro@4.7: Fix hash

- bucket/prismlauncher-qt5.json
- bucket/prismlauncher.json
- scripts/prismlauncher-qt5/install-associations.reg
- scripts/prismlauncher-qt5/uninstall-associations.reg
- scripts/prismlauncher/install-associations.reg
- scripts/prismlauncher/uninstall-associations.reg
Adds an optional associations registry file that supports the new feature to import mod-packs from the command line. https://github.com/PrismLauncher/PrismLauncher/pull/266
This also updates the launcher to v6.0 and switches to MSVC, as recommended by Scrumplex (a developer).
> prismlauncher/prismlauncher-qt5: Update to v6.0, add associations

- bucket/pegasus.json
Reason: In my testing on my computer: The previous checkver in this manifest did not always get the right version, or returned a regex error. This new checkver is always consistent, and it returns the correct version every time,
> pegasus: Fix `checkver` to be more reliable for version checking

- bin/test.ps1
- bucket/ppsspp-dev.json
- bucket/ppsspp.json
- Fix outdated `ppsspp(-dev)` manifests
- Update to Pester 5, See https://github.com/ScoopInstaller/Scoop/releases/tag/v0.3.1:
>### BREAKING CHANGES
>
>- **pester:** Update to Pester 5 (https://github.com/ScoopInstaller/Scoop/pull/5222)
>
>#### IMPORTANT FOR BUCKET MAINTAINERS
>
>- Pester 5 is used in this release. To make sure your bucket's CI works properly, please update `bin\test.ps1` from Pester 4 to Pester 5.
>- You can use `test.ps1` attached in the release files.
> ppsspp(-dev): Fix manifests, Update `test.ps1` to Pester 5

- bucket/ares.json
- Update to version 131
- Adds ARM architecture and adjusts the URLs accordingly
Checked to confirm that the overall structure is otherwise the same.
> ares: Update to version 131, add ARM64 architecture

- bucket/dgvoodoo2.json
You can use one Control Panel to configure all the games you are using dgVoodoo2 with. So having a shortcut to it make sense.
Closes #XXXX
> dgvoodoo2: Add shorcut

- bucket/raine.json
The DLL packages were updated on the 5th and 6th of January 2023.
> raine@0.94.10: Fix hashes for dependencies

- bucket/epic-games-launcher.json
This was done to allow the shortcut created by the installer to always point towards the 'current' directory instead of the version number '14.2.1'.
> epic-games-launcher: Change `pre_install` to `post_install`

- bucket/pcsx2-dev.json
It looks like PCSX2 has stopped using the `shaders\GS_FX_Settings.ini` file to store settings, causing an empty file to be created there when scoop installs the program. I believe the configuration has been moved to `inis\GS.ini` which is already persisted due to the entry for the `inis` directory.
Removing this line stops the unnecessary file from being created.
> pcsx2-dev: Remove unnecessary persist entry

- bucket/bgb.json
This commit updates the version number and required download checksums for the Game Boy emulator BGB to the latest version released on 2022-10-22
> bgb: Update to version 1.5.10

- bucket/ppsspp-dev.json
- bucket/ppsspp.json
- Remove `extract_dir`. Fixes #794 
- Remove `bin` as application is not a command-line app
- Add 32bit arch for `ppsspp`
> ppsspp(-dev): Remove extract_dir, bin, Add 32bit arch

- .github/ISSUE_TEMPLATE/package-request.yml
Just noticed the label in this repo is `new package`
Related to #796
> Rename `package-request` label to `new package` in issue template

- bucket/xenia-canary.json
the patches folder is needed to keep created patches after a version is updated.
Closes #XXXX
> xenia-canary: Persist `patches` folder

- bucket/steam-rom-manager.json
Adds [steam-rom-manager](https://github.com/SteamGridDB/steam-rom-manager) (1.2k stars), json file borrowed from [hermanjustnu/scoop-emulators](https://github.com/hermanjustnu/scoop-emulators/blob/master/bucket/steam-rom-manager.json) bucket with the following changes:
- Updated all links to use `https://github.com/SteamGridDB/steam-rom-manager` instead of `https://github.com/doZennn/steam-rom-manager` (redirects anyway there)
- Use ROM as full uppercase when used in titles
```diff
diff --git a/steam-rom-manager-orig.json b/steam-rom-manager.json
index 71465da1..4385e42a 100644
--- a/steam-rom-manager-orig.json
+++ b/steam-rom-manager.json
@@ -1,12 +1,12 @@
{
"version": "2.3.40",
"description": "Steam ROM Manager adds non-Steam games to steam in bulk and manages their artwork assets",
- …
```
> steam-rom-manager: Add version 2.3.40

- bucket/openttd.json
This adds `checkver` and `autoupdate` properties to the OpenTTD manifest.
I have also used the `checkver` tool to update the manifest to v13.0 (after my own changes).
Closes #817. Related to #413 from 2021 which has not been merged yet.
> openttd: Update to version 13.0, add checkver and autoupdate

- bucket/crewchief.json
From my personal scoop bucket https://github.com/scowalt/scoop-apps/blob/main/bucket/crewchief.json
I've tested autoupdate. I've also installed and been running this from my personal bucket for a bit
> crewchief: Add version 4.16.3.5

- bucket/flycast.json
Version 2.1 uses a capitalized V in the version tag, unlike previous releases. This caused autoupdate to fail.
I changed the autoupdate url to use a capital V, ran checkver, then reverted it to an uncapitalized v, since I assume this was a one-time mistake, and future releases will use the uncapitalized letter again.
> flycast: Update to version 2.1

- bucket/tf2-hud-editor.json
> tf2-hud-editor: Update to version 3.1, fix `extract_dir`

- .vscode/settings.json
- bucket/pcsx2-dev.json
https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4288 dropped AVX2 builds which broke autoupdate.
> pcsx2-dev: Update to version 1.7.4436

- .vscode/settings.json
Without this option, vscode removes newlines which causes tests to fail.
> (chore): Ensure vscode saves newlines

- bucket/rmg.json
Rosalie's Mupen GUI is a free and open-source mupen64plus GUI written in C++.
> rmg; Rosalie's Mupen GUI: Add version 0.4.0

- bucket/bloxstrap.json
The developer no longer supports 32bit version, because the Roblox client is now 64bit.
> Bloxstrap: Remove 32bit version and update to 2.3.0

- bucket/nethack.json
The developers have stopped uploading releases to Github. This PR changes the download url to the nethack site, and introduces hash checking.
> nethack: update to 3.6.7 and use official site for download, add hash checking

- bucket/alephone-marathon-trilogy.json
Added Aleph One (Marathon Trilogy) package version 20230529.
No persistable data; user data is saved to %USERPROFILE%/Documents/Aleph One
Closes #991
> alephone-marathon-trilogy: add version 20230529

- bucket/duckstation-preview.json
- bucket/duckstation.json
Duckstation updated their config directories around a year ago. Update to be aligned with those changes and properly persist settings on update.
[Config Definitions](https://github.com/stenzek/duckstation/blame/2d78b3f26a18600cbeb1f7add97f345d7345deeb/src/core/settings.cpp#L1309)
[Relevant Commit](https://github.com/stenzek/duckstation/commit/b42b5501f69329a6b808e939c1e26918e3d59a96#diff-a476025c9c14eb09c2b1798d364d676742cd7ea831e5b749b292ad383c490cbcR1150)
> duckstation: Fix persist

- bucket/prismlauncher-qt5.json
- bucket/prismlauncher.json
this implements the portable versions of prismlauncher packages into scoop, which allows for the use of `persist` directories, as well as having both versions installed at the same time with separate data directories. for backwards compatibility, `%APPDATA%\PrismLauncher` is also copied to `persistdir` during a fresh install/when no files are already in `persistdir`
> prismlauncher/prismlauncher-qt5@7.1: start using portable binaries

- bucket/loot.json
Fixed autoupdate since 32-bit support was dropped.
https://loot.readthedocs.io/en/latest/app/changelog.html
>Removed
>Support for Windows 7 and 8.1, and 32-bit Windows 10. LOOT now requires 64-bit Windows 10 or 11.
> loot: Update to version 0.20.0

- bucket/ares.json
The newest version omitted ending with “-msvc-x64” for the x64 architecture.
It's unclear if the change is here to stay, but it's the reason the manifest wasn't updated automatically to the latest version, hence this PR.
> ares: Update to version 133

- bucket/dxvk.json
This makes sure that the dirs for the different architectures are what you see when entering the root folder for the software – rather than just another dir with the software name and the current version appended, which is simply redundant.
Closes #1018
> dxvk: Add extract_dir property

- bucket/battlenet.json
This is my attempt to add Battle.net, which is currently a non-portable app. The app requires admin rights to install and uninstall.
This PR closes #1016, and as suggested the version of the app has been changed to `nightly`. This shouldn't be a problem since it updates itself.
> battlenet: Add version nightly (2.25.1.14443)

- bucket/goggalaxy.json
Changes the installation and uninstallation of the app, from using `InnoSetup` to a script with silent installation switches. This PR Closes #907 since now Gog Galaxy can be opened.
During my experimentation, I have seen that some folders don't get deleted after the uninstallation, so I also made those folders persistent in the manifest.
> goggalaxy@2.0.72.94: Fix goggalaxy manifest

- bucket/jazz2-resurrection.json
Changes to the manifest include:
- Changing the license to GPL 3.0 only as I don't see any mention of GPL 3.0 or later
- Updates the notes to reflect the current setup process, as well as general improvements to the contents
- Adds the architecture property for extract_dir, providing both x32 and x64 versions of the app
- Provides shortcuts to all versions of the app; standard, AVX2 and SDL2
- Persists both the Source dir (where you put all the game data) and the config file (automatically created through pre_install if one doesn't exist), making the installation completely portable
> jazz2-resurrection: Update to version 2.1.0

- bucket/steam.json
Since other stores like Epic Games, GOG and Battle.net are in place, it only makes sense to add the most popular one as well.
Credit goes to the original author @rashil2000 over on the [versions bucket](https://github.com/ScoopInstaller/Versions).
I made smaller adjustments as I saw fit, mainly omitting the mention of creating a separate library folder (worded as “HIGHLY recommended”), as that option is presented every time you install a game.
I also removed the _-dev_ argument from the shortcut since any arguments should be up to the individual user – not applied by default, at least not something that's not necessarily universally desired. ([Reference](https://developer.valvesoftware.com/wiki/Command_line_options#Command-Line_Parameters))
> steam: Add nightly version

- bucket/prismlauncher.json
this disables the builtin updater introduced in 8.0, allowing scoop to continue to manage prism by itself.
> prismlauncher@8.0: disable built-in updater

- bucket/infraarcana.json
Closes #1056
Note that this is likely not a real final fix but opening it as a draft - the real final fix is probably something like:
```
ia-windows-x64-v21.0.1-$matchCommit-$matchYear-$matchMonth-$matchDay
```
But I don't know how to test that. According to https://github.com/ScoopInstaller/Scoop/issues/2263#issuecomment-389853826 the ext_dir variables are substituted in the auto_update
> fix infraarcana install

- bucket/gzdoom.json
Relates to #1051
GZDoom moved from https://github.com/coelckers/gzdoom -> https://github.com/ZDoom/gzdoom.
This corrects those URLs and the links to the correct download.
Note it doesn't necessarily close #1051, as there are two other issues there:
1. The autoupdate bot didn't detect download failure in this case, according to the issue.
2. The Windows artifact for release 4.11.3 changed from `gzdoom-4-11-3-Windows-64bit.zip` -> `gzdoom-4-11-3.a.-Windows-64bit.zip`. Hash is also different. This pull request reflects the changed name, but I don't think the autoupdate mechanism could handle such a manual change.
> gzdoom: Update GitHub URLs

- bucket/romsorter.json
Also updates grammar and the like in the `description` and `notes`.
The latest download URL of the app uses its version at the tail end.
I've also created [an issue](https://github.com/drakewill-CRL/ROMSorter/issues/5) regarding portable mode, as the config of the app is currently created in **Local AppData**.
> romsorter: Update URL/Autoupdate

- bucket/jazz2-resurrection.json
- Manually downloaded through the same URL; hash checks out with what was reported as actual when attempting to update through Scoop.
> jazz2-resurrection@2.5.0: Fix hash

- bucket/scummvm.json
ScummVM has changed the structure of the zip, the app is now in a folder inside the zip. This adds a pre_install step to move the contents of this folder into the installation directory.
Also fix the persistence of the ini file, it was being created as a folder and not a file.
Closes #1073 and closes #1094
> scummvm: Fix installation path and ini file

- .github/workflows/pull_request.yml
benefit from https://github.com/ScoopInstaller/GithubActions/pull/39
I forgot this bucket not under the ScoopInstaller org. xD
Closes #XXXX
> chore(ci): switch to `pull_request_target` trigger

- bucket/ps3-system-software.json
Current regex missed latest [4.91](https://www.playstation.com/en-us/support/hardware/ps3/system-software/) update because of different case in title, added case-insensitive flag to prevent that in future.
> ps3-system-software: fix autoupdate

- bucket/freeorion.json
Adding the #/dl.zip back to the autoupdate and base url
> freeorion 0.5.0.1: Fix `url`

- bucket/pathofbuilding-community.json
Update PathOfBuilding-Community version to the latest available.
And fix the autoupdate URL, as they removed the version part of the downloaded file.
> Update PathOfBuilding-Community to v2.40.1 & fix autoupdate

- bucket/demulshooter.json
Manual update to version 12; the `autoupdate` section would need `$cleanVersion` at the end, while more likely than not, `$version` will continue to work going forward, since everything points to the next version being called 12.1, with the URL following that.
> demulshooter: Update to version 12

- bucket/dreamm.json
Add manifest for [DREAMM](https://aarongiles.com/dreamm/).
Description borrowed from official website:
> DREAMM is a specialized emulator for playing many of your original DOS, Windows, and FM-Towns LucasArts games with full fidelity to the original.
App supports [portable mode](https://aarongiles.com/dreamm/docs/v21/#install-portable), hence `config.json` is being created during `pre_install` section to enable it, together with 4 [documented](https://aarongiles.com/dreamm/docs/v21/#install-data) directories for holding generated files being added to persisted files & directories.
Closes #1036
> dreamm: Add version 2.1.2

- bucket/assetstudio.json
[Upstream repository](https://github.com/Perfare/AssetStudio) has been archived since 2023 Jan 21 and is no longer compatible with asset bundles generated by recent versions of Unity. zhangjiequan's fork seems the most active successor.
> assetstudio: Redirect to successor fork

- bucket/blade-of-agony.json
- bucket/freedoom.json
- bucket/speed-dreams.json
`dl_with_cache` was renamed to `Invoke-CachedDownload` in [#5173](https://github.com/ScoopInstaller/Scoop/pull/5143), this was causing decompression error during installation of the next apps: `blade-of-agony`, `freedoom` and `speed-dreams`.
Closes #876
Closes #1004
> fix: rename dl_with_cache to Invoke-CachedDownload

- bucket/freedoom.json
freedoom-manual.pdf is now called freedoom-manual-en.pdf
> freedoom: fix creating shortcut

- bucket/battlenet.json
The alternative to this checkver approach would be downloading the file yourself and using `(Get-Item setup.exe).VersionInfo.ProductVersion`, brew parses the plist file anyway, so we may as well just use that and save the 5MB installer download every actions run.
Fixes #1105
> battlenet: Refactor

- bucket/battlenet.json
Sometimes the $dir/.battlenet dir exists,
and sometimes it doesn't, Idk why,
but it's accounted for now.
```pwsh
Remove-Item:
Line |
9 |  Remove-Item $setup, "$dir/.battlenet" -Recurse
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot find path '~\scoop\apps\battlenet\1.18.10.3141\.battlenet' because it does not exist.
```
> battlenet: Fix pre_install

- bucket/dolphin-beta.json
- bucket/dolphin-dev.json
- bucket/dolphin.json
[here is what is does](https://github.com/dolphin-emu/dolphin/pull/10252)
P.S. is there a way to specify the branch used for a bucket? the only way i was able to test this is by setting dolphin to my default branch
> adds DolphinTool.exe to dev and beta dolphin json files (normal doesn't seem to have DolphinTool.exe)

- bucket/openttd.json
The original manifest file has an error. Win64 and win32 versions are swapped thus it will cause errors on 32-bit computers. Furthermore, the game has arm64 builds provided, so I think it is better to fix the architecture.
This manifest is basically identical with [this manifest](https://github.com/WenSimEHRP/OpenTTD-bucket/blob/master/bucket/openttd.json). I just changed the notes.
Baseset installation (i.e. OpenGFX, OpenMSX, and OpenSFX) are removed because the basesets can be downloaded afterwards, and the game stores them in the user documents folder, in which it is the default content storage folder (all screenshots, mods, basesets, etc.) Plus, the user (e.g. many who have the original TTD graphics, musics and sounds OR they installed the game before) may already have the basesets …
> OpenTTD: fix architecture and remove baseset installation

- bucket/bedrockupdater.json
This program/project/application allows one to download, install and update Minecraft: Bedrock Edition (Release & Preview) without the Microsoft Store.
> [!CAUTION]
> This project doesn't allow you to pirate Minecraft: Bedrock Edition, you must own it.
> DRM exists at the game level, if a Microsoft Account that owns the game doesn't exist, the game refuses to start.
> Add Bedrock Updater.

- bucket/ppsspp-dev.json
Changed the builds server to the one currently used, removed extract_dir and added ARM64 builds.
Closes https://github.com/Calinou/scoop-games/issues/1145, https://github.com/Calinou/scoop-games/issues/794 (794 was already closed but the issue appears to still be a thing on ppsspp-dev)
> ppsspp-dev: Add ARM64, fix checkver, autoupdate, remove extract_dir

- bucket/steam-achievement-manager-syntaxtm.json
The zip filename changed, so the automatic updater didn't update. Also changed how it shows up on the start menu
> steam-achievement-manager-syntaxtm: autoupdate fix for 0.6.0, name change

- bucket/dungeonsupdater.json
Dungeons Update provides an alternative way to download Minecraft Dungeons by allowing one to download game files without the need of the Minecraft Launcher or Xbox App.
> [!NOTE]
> - DRM is performed at application level.
> - The project doesn't allow for piracy in anyway.
> - The project fetches the Launcher version of Minecraft Dungeons.
> - The Launcher/Microsoft Store versions of Minecraft Dungeons seem to have been merged under the name of [Minecraft Dungeons for Windows](https://www.xbox.com/games/store/minecraft-dungeons-for-windows/9P8MK4NC0LJB).
> - If a Microsoft account owns Minecraft Dungeons for Windows then the account has effective access to both the Microsoft Store/PC Game Pass + Launcher versions of the game.
> Add Dungeons Updater.

- bucket/lime3ds.json
This should fix the exception. I also checked that the app still uses this naming scheme in the latest version.
> lim3ds@2115: Fix extract_dir and add it to autoupdate

- bucket/prismlauncher.json
The files accounts.json, prismlauncher.cfg, and metacache weren't properly persisted.
Added SymbolicLink line to the pre_install script part, removed the files from the inbuilt persist list.
Relates to #1065
> Change Prismlauncher persist files to symlink

- bucket/dolphin.json
On top of changing the version number schema and the URL pattern to the downloads, the Dolphin emulator team also changed the structure of the archive, so the installation was failing because now everything, including the main executable, is inside a folder named `Dolphin-x64\`. This PR fixes that.
Relates to #1176
> Dolphin: fix bin and shortcut to executable due to change in the archive structure

- bucket/daggerfallunity.json
Daggerfall Unity expects `.dfmod` files to be stored within a subfolder of StreamingAssets. Failing to persist this folder means users will lose any installed mods any time the app updates.
Also persisting GameFiles in case users want to place Daggerfall's arena2 folder there and create a truly portable install.
> daggerfallunity: persist mods and gamefiles

- bucket/opentyrian2000.json
Changes:
- persist config files and save data
- automatically download freeware game data files
- remove notes field
Closes #1185
> OpenTyrian2000: game data and persistence

- .vscode/settings.json
- bucket/zandronum.json
Add missing `pre_uninstall` and `post_uninstall` entries to sortJSON field list in settings.json.
Closes #1183
> Update settings.json: add pre/post_uninstall fields to sortJSON lists

- bucket/alephone-marathon-trilogy.json
Marathon executables were renamed to "Classic Marathon", which broke the shortcuts.
> Fix broken Marathon Shortcuts

- bucket/warzone2100.json
List all architectures for Warzone 2100, not just the x86 / 32-bit version.
> warzone2100@4.5.0: offer all architectures

- bucket/xonotic.json
Updates the manifest for `xonotic`.
This commit does 3 things:
This version has been released for quite a while, but the autoupdate hasn't been working.
For reasons I did not dig into, the installation of this package is failing. [One user is saying that this may be a bug in scoop](https://github.com/Calinou/scoop-games/issues/877#issuecomment-1566091669).
Whatever the cause may be, removing the `extract_dir` directive from the manifest fixes this issue. With this change, the package will be installed into an unnecessary subdir, but at least it works.
Closes #877.
The download page that the previous version would parse for a version number and hash apparently has changed.
> xonotic: Update to version 0.8.6, skip extract_dir, and fix autoupdate

- bucket/trenchbroom.json
changed dependency to "extras/vcredist2022" since "extras/vcredist2015" does not seem to exist anymore
Closes #1066
- [ x] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).
> Update trenchbroom.json vcredist2015 dependency

- bucket/gzdoom.json
- Updates to version 4.12.2
- Omits the "-64bit" part of the URL, since the latest versions only support 64 bit and therefore don't type it out in the filename.
(The last part should be the reason the manifest wasn't updating properly.)
> gzdoom: Update to version 4.12.2 and fix URL

- bucket/hedge-mod-manager.json
A simple mod manager for Sonic games
> hedge-mod-manager: Add version 7.12-9

- bucket/mcrcon.json
Mcrcon manifest in this bucket is not working. I created manifest for it by myself some time ago for my personal Scoop bucket, and I believe it should replace this one.
Changes::
- fix that decompress error
- x64 and x86 support (instead of only x86)
Closes [#851](https://github.com/Calinou/scoop-games/issues/851)
> Mcrcon: Repair manifest

- bucket/lime3ds.json
Fixes issue caused by renamed/removed binaries
https://github.com/Lime3DS/Lime3DS/releases/tag/2118
```
Linking ~\scoop\apps\lime3ds\current => ~\scoop\apps\lime3ds\2118
Creating shim for 'lime3ds-cli'.
Get-Command: ~\scoop\apps\scoop\current\lib\install.ps1:757
Line |
757 |              $bin = (Get-Command $target).Source
|                      ~~~~~~~~~~~~~~~~~~~
| The term 'lime3ds-cli.exe' is not recognized as a name of a cmdlet, function, script file, or executable
| program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
| again.
Can't shim 'lime3ds-cli.exe': File doesn't exist.
```
> lime3ds: fix bin and shortcuts

- bucket/pcsx2-dev.json
- bucket/pcsx2.json
> Update pcsx2.json and pscsx2-dev.json

- bucket/osulazer.json
OSU migrated updater from Squirrel to Velopack since [2024.906.1](https://github.com/ppy/osu/releases/tag/2024.906.1)
This caused the file path changed from `/lib/net45` to `/lib/app`.
https://github.com/ppy/osu/issues/29783#issuecomment-2336649935
```bash
❯ scoop install osulazer
Installing 'osulazer' (2024.906.2) [64bit] from 'games' bucket
Loading osulazer-2024.906.2-full.nupkg from cache.
Checking hash of osulazer-2024.906.2-full.nupkg ... ok.
Extracting osulazer-2024.906.2-full.nupkg ... Could not find 'net45'! (error 16)
発生場所 C:\****\Scoop\apps\scoop\current\lib\core.ps1:889 文字:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Could not …
```
> Fix OSU extract_dir

- bucket/rvgl.json
> rvgl: add hash checking and persists

- bucket/supermodel.json
Added supermodel package version 0.3a-git-f9cb795.
The versioning string for the newest development versions of Supermodel is random, but the Supermodel download page sorts the builds in order of newest, so we only need to capture the first match to get the newest version. 
Supermodel in Scoop has to be run using a wrapper script that temporarily sets the working directory to the executable location, as Supermodel is hardcoded to load configuration files relative to the executable. As far as I could see, there are no Scoop options yet for being able to set the working directory of an entry in the bin field. 
Closes #681
> supermodel: add version 0.3a-git-f9cb795

- bucket/openfortress.json
> Openfortress: Add version 21

- bucket/steam-art-manager.json
Manifest now uses the updated naming scheme, version updated to 3.10.5. Autoupdates should work from here on.
Closes #1248 
- [✅] I have read the [Contributing Guide](https://github.com/Calinou/scoop-games/blob/master/CONTRIBUTING.md).
> Update Steam Art Manager to version 3.10.5

- bucket/steam-art-manager.json
Fixed autoupdate URL. HOPEFULLY my final pull request for this same issue, your patience has been appreciated!
Relates to #1272
> steam-art-manager: Fix autoupdate URL

- bucket/cemu-dev.json
Closes #1278
> Since cemu has stopped making experimental releases and started making pre-releases for major versions, the cemu-dev package should point to the latest pre-release, which is 2.4 as of this issue.
> Update cemu-dev to use latest pre-release

- bucket/raze.json
Raze was stuck on 1.9.1 because the name format changed.
> Fix broken autoupdate url for Raze

- bucket/duckstation-preview.json
- bucket/duckstation.json
Closes #1251 and #1268. 
Duckstation doesn't want to open in a junction folder, so I made its shortcut point to the original folder.
I also used the archive.org link for the BIOS wiki page. I would have used a different wiki or comparable link, but could not find anything with a quick search.
> duckstation-preview: fix shortcut issue, update bios link

- bucket/tf2classic.json
> Tf2classic: Add version 2023-05-27

- bucket/ryujinx.json
The autoupdate url used a fixed version in the name of the artefact which made it useless and broken. Using `$version` now. 
And update to `1.2.78` cuz otherwise it doesn't pass the checks.
> Ryujinx@1.2.76: fix version string in autoupdate url and update

- bucket/gzdoom.json
Fixed the gzdoom download url and the associated file hash.
Current url: https://github.com/ZDoom/gzdoom/releases/download/g4.14.0/gzdoom-4-14-0-Windows.zip
Correct url: [https://github.com/ZDoom/gzdoom/releases/download/g4.14.0/gzdoom-4-14-0a-windows.zip](https://github.com/ZDoom/gzdoom/releases/tag/g4.14.0)
Closes [#1299](https://github.com/Calinou/scoop-games/issues/1299)
> gzdoom@4.14.0: Fixed gzdoom download url and hash

- bucket/scummvm.json
In new ScummVM release executable doesn't include version like that was it previous release, i.e. `scummvm.exe` instead of `scummvm-2.9.0.exe`. Because of this renaming added in #1124 results in error during installation (it still ends up successful). I think it's probably better to wrap rename command with condition in case user wants to install older version.
Here's installation log without change:
```
Updating one outdated app:
Updating 'scummvm' (2.8.1 -> 2.9.0)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: ff6093|OK  |   5.5MiB/s|C:/Users/User/scoop/cache/scummvm#2.9.0#83bb47a.zip
Download: Status Legend: …
```
> scummvm: rename if there's version in file name

- bucket/xemu.json
The post_install script currently overwrites the entirety of `xemu.toml` regardless of whether or not it contains any existing data. This PR modifies the script so that it checks to see if the file is empty or not (and only writes to it if it is).
> xemu: Fix post_install script overwriting config file even when not empty

- bucket/sokoban.json
- Changed the license from "MIT|Apache-2.0" to "Apache-2.0" in the sokoban.json file
> sokoban: update license to Apache-2.0

- bucket/mesa3d-mingw.json
- bucket/mesa3d.json
Closes #1262
Since `systemwidedeploy.cmd` and `perappdeploy.cmd` might break the system, no `post_install`, a note is displayed instead.
I'm unsure if the naming is proper since this is not an official Mesa project.
> mesa3d & mesa3d-mingw: Add version 24.3.3

- bucket/0ad.json
New 0ad release: https://play0ad.com/new-release-0-a-d-alpha-27-agni/.
Second attempt. New versioning scheme required a minor changes to the spec. This is likely to change again when 0ad reaches v28.
> 0ad: Update to version 0.27.0

- bucket/shadps4.json
shadps4 releases are tagged with an additional dot, which is included in
the extracted version when using the github checkver.
Using the url checkver with a small regex cleanup we can extract the
correct version that actually fits nicely into the autoupdate url.
Relates to #1290 #1291
> fix: shadps4 checkver

- bucket/bzflag.json
The original BZFlag 2.4.28 installer that I uploaded was corrupted, so the hash that was pulled into scoop-games was incorrect.  I uploaded a corrected installer file and I corrected the hash. The manifest also referenced extra/vsredist2017, which doesn't exist anymore, so I replaced that with extra/vcredist2022.
> Fix BZFlag 2.4.28 hash and switch the vcredist

- bucket/stonecutter.json
Minor update to the manifest that allows `Stonecutter.exe` to be invoked via the PATH.
[v1.8.5](https://github.com/Aetopia/Stonecutter/releases/tag/v1.8.5) allows the executable to accept the Minecraft URI protocol via the command line.
Relates to #1199
> Add PATH support for Stonecutter.

- bucket/xxmi.json
Adds XXMI, a model importer for Gacha Games (namely Wuthering Waves, Genshin Impact, Zenless Zone Zero and Honkai: Star Rail)
Persists are the absolute necessities to keep mods and other resources persisted
Shims and Shortcuts as necessary
> xxmi: Add version 1.5.0

- bucket/stonecutter.json
Decided to remove URI protocol support from Stonecutter, a last minute change hence no longer requiring `PATH` support.
The original intentional was to provide users with granular control over how MCBE launched via Stonecutter's executable alongside the fixes it provided.
After careful consideration, I thought it would be best to modularize the project itself providing more control to users & that modularization be its own repository hence the rollback. 
Relates to #1335
> Remove PATH support for Stonecutter.

- bucket/mudlet.json
This PR updates the package to the newest version as well as modifies the download and autoupdate to use the new URL and page layout.  It also adds a split for 32/64-bit.
Closes #1333
> mudlet: Update to 4.19.1 and fix download url, autoupdate and add 32/64-bit split

- bucket/ryujinx-canary.json
- bucket/ryujinx.json
Ryujinx project have moved to their own GitLab platform for development.
The current Ryujinx package links to incorrect packages, so updates do not work.
There are already PRs to fix the issue, linked below.
My version is differs in checkver, it uses GitLab instance API to get the latest version. And I also add Canary release package.
Closes [#1337](https://github.com/Calinou/scoop-games/issues/1337)
Relates to [#1346](https://github.com/Calinou/scoop-games/pull/1346) [#1339](https://github.com/Calinou/scoop-games/pull/1339)
> ryubing-ryujinx: init at 1.2.86

- bucket/raze.json
The Raze zip changed names (1.11.0 to 1.11.0a) but the version in the url path was unchanged (still 1.11.0), so now the link and the autoupdate pattern are broken.  ~I think the new name is not proper, so it's better to make a one time patch instead of changing the pattern, and have autoupdate take care of the next one~ Updated with a better solution that handles this weird url
> Patch raze to use hotfix zip.

- bucket/shadps4-dev.json
Closes #1290.
It seems that the url setting for the autoupdate rule was wrong, the architecture property was used incorrectly. I tested this change and it seems to fix the issue.
> shadps4-dev: fix autoupdate url

- bucket/xenia-canary.json
- bucket/xenia.json
Updates xenia-canary.json to:
- Slightly change description to match upstream
- Change homepage to GitHub repo (current one does not refer to canary version of xenia)
- Fixes licence url (change to main branch)
- Uses architecture property to meet scoop manifest guidelines
- Includes new cache folders in persist
- Fixes checkver and autoupdate urls (old location retired).
Updates xenia.json to slightly change description to match upstream.
Closes #1361
> xenia-canary: Fix autoupdate & xenia: slight update to manifest description

- bucket/azahar.json
- bucket/reloaded-ii.json
The current licence identifiers for `azahar` and `reloaded-ii` are incorrect, this PR remedies that.
Relates to #1360 & #1362
> azahar@2120.2: Licence fix & reloaded-ii@1.28.8: Licence fix

- bucket/duckstation-preview.json
- bucket/duckstation.json
Updates `duckstation.json` app manifest to:
- Slightly change description to match upstream description
- Change homepage to project webpage
- Updated licence to current project licence
- Inform user by suggesting vcredist dependency
- Uses architecture property to add arm64 build in addition to 64bit build
- Adds bin property as app supports command line parameters
- Adds a pre-install script to migrate any existing user data to persist directory
- Modifies autoupdate with the addition of the arm64 build
All changes are also mirrored on `duckstation-preview.json`.
Closes #1365
> duckstation: Fix licence and add arm64 build

- bucket/prismlauncher.json
This PR adds `skins` to the list of persisted folders on the Prism Launcher manifest.
Closes #1342
> prismlauncher: Persist skins folder

- bucket/xenia-canary.json
Changes made in this PR:
- Added persist for cache_host folder
- Added persist for recent.toml file
- Removed persist for cache0 folder
- Removed persist for cache1 folder
The cache0 & 1 folders do not require persistence as they do not contain any data that would aide running (or even re-running) games on xenia-canary. 
> xenia-canary: Fix persists

- bucket/ryujinx-canary.json
- bucket/ryujinx.json
GitHub workflow failed to fetch the latest version of `Ryujinx`.
1. Update `Ryujinx` to `1.3.1`.
2. Update checkver for `Ryujinx` and `Ryujinx-canary`.
Closes #1381
> ryujinx: fix checkver

- bucket/epic-games-launcher.json
- `epic-games-launcher`: Fix `post_install` & `pre_uninstall` script failure when there are spaces in the installation path.
Closes #1344
> epic-games-launcher: Fix post_install & pre_uninstall script

- bucket/playit.json
This PR makes the following changes to `playit`:
1. Update to version `0.15.26`.
2. Update license & Optimize description.
3. Add 32bit arch support & Fix 64bit arch.
4. Fix checkver.
5. Fix installation.
Closes #1343
> playit: Update to version 0.15.26

- bucket/runelite.json
This PR makes the following changes to `runelite`:
- Add arm64 arch.
- Fix installation failure.
Closes #1232
> runelite: Add arm64 arch & fix installation failure (#1232)

- bucket/project64-dev.json
The `Expand-InnoArchive` function is not triggered for non-`.exe` files, despite the `innosetup` parameter being enabled.
This PR makes the following changes to `project64-dev`:
- Update `download url` & `autoupdate url` to fix installation failure.
Closes #1394
> project64-dev: Fix installation failure

- bucket/undertale-mod-tool.json
- Reomve extra comma in `undertale-mod-tool.json` to fix installation.
Relates to #1383
> undertale-mod-tool: Fix installation

- bucket/assetstudio.json
> PS >> assetstudiogui.exe 
> You must install .NET to run this application.
> 
> App: D:\Scoop\apps\assetstudio\current\AssetStudioGUI.exe
> Architecture: x64
> App host version: 6.0.25
> .NET location: Not found
AssetStudio in games bucket is a `.NET 6.0` version.
> {
>     ......
>     "url": ".../download/v0.16.53/AssetStudio.net6.0-windows_v0.16.53.zip",
>     ......
> }
It requires `.NET 6.0` to work properly: https://github.com/zhangjiequan/AssetStudio?tab=readme-ov-file#requirements
This PS makes the following changes:
- Add `suggest` for `assetstudio`.
> assetstudio: add suggest

- bucket/ryujinx-canary.json
- bucket/ryujinx.json
- Add `arm64 arch` & `suggest` for `ryujinx` and `ryujinx-canary`.
> ryujinx: Add arm64 arch & suggest

- bucket/chiaki-ng.json
This PR does the following:
- Adds an arm64 build
- Switches the x64 build to the MSYS2 version (as VC version no longer exists)
- Fixes licence
> chiaki-ng: Add arm64 build, switch x64 to MSYS2 build

- bucket/cambridge.json
- `cambridge@0.3.4`: Fix urls, fix hash.
> cambridge@0.3.4: Fix urls, fix hash

- bucket/endless-sky.json
- `endless-sky`: Update to version 0.10.12, remove 32bit arch, fix urls.
> endless-sky: Update to version 0.10.12, remove 32bit arch, fix autoupdate

- bucket/doomrunner.json
- `doomrunner`: Update to version 1.9.1, fix autoupdate.
> doomrunner: Update to version 1.9.1, fix autoupdate

- bucket/katrain.json
- `katrain`: Update to version 1.16, fix autoupdate.
> katrain: Update to version 1.16, fix autoupdate

- bucket/angband-dev.json
- `angband-dev`: Update to version 4.2.5-389-g1b3978f8d, fix checkver.
> angband-dev: Update to version 4.2.5-389-g1b3978f8d, fix checkver

- bucket/dolphin-dev.json
- `dolphin-dev`: Update to version 2503a-603, add arm64 arch, fix checkver, fix autoupdate.
> dolphin-dev: Update to version 2503a-603, fix checkver

- bucket/dwarf-fortress-lnp.json
- `dwarf-fortress-lnp@0.47.05-r11`: Fix urls.
> dwarf-fortress-lnp@0.47.05-r11: Fix urls

- bucket/megamek-dev.json
- bucket/megamek.json
- bucket/megameklab-dev.json
- bucket/megameklab.json
- bucket/mekhq-dev.json
- bucket/mekhq.json
- `megamek(-dev), megameklab(-dev), megahq(-dev)`: Update to version 0.50.06, fix checkver, fix autoupdate, add hash, add extract_dir.
> megamek(-dev), megameklab(-dev), megahq(-dev): Update to version 0.50.06, fix checkver, fix autoupdate, add hash, add extract_dir

- bucket/endless-sky.json
- `endless-sky@0.10.12`: Fix shortcuts, remove bin.
Relates to #1413
> endless-sky@0.10.12: Fix shortcuts, remove bin

- bucket/extremetuxracer.json
- bucket/gdsdecomp.json
- bucket/infraarcana.json
- bucket/lambdahack.json
- bucket/lzdoom.json
- bucket/mameui.json
- bucket/openmsx-dev.json
- bucket/prboom-plus.json
- bucket/prismlauncher-qt5.json
- bucket/rbdoom-3-bfg.json
- bucket/rimpy-pre-release.json
- bucket/rimpy.json
- bucket/rvgl-launcher.json
- bucket/stella.json
- bucket/tf2classic.json
- bucket/tome4.json
- bucket/trenchbroom.json
- bucket/umod.json
- bucket/yquake2.json
- `prismlauncher-qt5@7.2`: fix checkver.
- `rvgl-launcher@0.1.23.1030a3`: fix checkver, fix autoupdate.
- `tf2classic@2_r53`: fix checkver, fix autoupdate.
- `tf2classic`: Update to version 2.2.2, add hash, fix checkver, fix autoupdate.
- `mameui`: Update to version 0.277.0, fix checkver, fix autoupdate.
- `rbdoom-3-bfg`: Update to version 1.6.0, fix checkver, fix autoupdate.
- `prboom-plus`: Update to version 2.6.66, fix arch, fix checkver, fix autoupdate.
- `lzdoom`: Update to version 4.11.4, fix checkver, fix autoupdate.
- `openmsx-dev`: Update to version 20.0-469-g3534a1d3c, fix checkver, fix autoupdate.
- `stella`: Update to version 7.0, fix shortcuts, fix checkver, fix autoupdate.
- `tome4`: Update to version 1.7.6, fix checkver.
- …
> Fix manifests

- bucket/fishstrap.json
This pull request adds the addition of Fishstrap (a fork of Bloxstrap) to scoop. I have been requested a few times over on GitHub/ Discord, so I thought I would take up the issue as I wanted it on scoop myself.
closes #1324
> Fishstrap: add version 2.9.1.2

- bucket/melonds.json
@Calinou sorry, #1431 has a [mistake](https://github.com/Calinou/scoop-games/issues/1430#issuecomment-2937159498)
Since `melonds.toml` doesn't exist initially, it's created by scoop as a folder, including when you `scoop update --force melonds` with the file _already existing_, apparently. Looks like `melonds.ini` already had special handling for not existing during install.
I modified the manifest locally this time and did `scoop update --force melonds` again. It correctly deleted the invalid _folder_ symlink created by running #1431, and set up the toml file correctly. Melonds functioned normally on its first run after this upgrade, including storing changed settings in the toml file.
One thing I'm not sure how to test correctly now is the case of someone with a <1.0 version with …
> melonds: fix incorrect persistence logic

- bucket/ryujinx-canary.json
- bucket/ryujinx.json
Ryujinx has recently [migrated](https://git.ryujinx.app/ryubing/ryujinx/-/commit/0652d7e7402b5d32ada8c276912f818ba7195364) their release repository to [gitlab](https://git.ryujinx.app/ryubing/ryujinx/-/releases) and has removed win-arm64 releases.
> ryujinx: The remote server returned an error: (404) Not Found.
> URL https://api.github.com/repos/Ryubing/Stable-Releases/releases/latest is not valid
> ryujinx-canary: 1.3.73 (scoop version is 1.3.62) autoupdate available
> Autoupdating ryujinx-canary
> ......
> URL https://github.com/iurehg8uetgyh8ui5e/cr/releases/download/1.3.73/ryujinx-canary-1.3.73-win_arm64.zip is not valid
> ERROR Could not update ryujinx-canary, hash for ryujinx-canary-1.3.73-win_arm64.zip failed!
- `ryujinx@1.3.1`: Fix checkver, …
> ryujinx(-canary): Update URLs, drop arm64 support

- bucket/shadps4-dev.json
- `shadps4-dev`: Update to version 2025-06-06-91d2945, fix checkver, fix autoupdate.
Closes #1445
> shadps4-dev: Update to version 2025-06-06-91d2945, fix checkver

- bucket/dolphin.json
- bucket/extremetuxracer.json
- bucket/vkquake.json
- bucket/vkquake2.json
- chore: Replace vcredist2015-2019 with 2022, since vcredist2015-2019 has been deprecated in extra bucket. https://github.com/ScoopInstaller/Extras/commit/6dd50d15488d67ba96c1b7af012ea5b9401ab590
- `extremetuxracer@0.8.4`: Restore the suggestion mistakenly deleted in #1427.
> (chore): Replace vcredist2015-2019 with vcredist2022

- bucket/unciv.json
> unciv: 4.16.14 (scoop version is 4.16.13) autoupdate available
> Autoupdating unciv
> The remote server returned an error: (404) Not Found.
> URL https://github.com/yairm210/Unciv/releases/download/4.16.14/Unciv-Windows64.zip is not valid
> ERROR Could not update unciv, hash for Unciv-Windows64.zip failed!
[unciv@4.16.13-patch1](https://github.com/yairm210/Unciv/releases/tag/4.16.13-patch1) and [unciv@4.16.14 (source-only)](https://github.com/yairm210/Unciv/releases/tag/4.16.14) is now available.
The current `checkver` will cause the automatic updater to fail to get the release version with `-patch` postfix or get the wrong release version with source code only.
- `unciv`: Fix checkver.
> unciv: Fix checkver

- bucket/zelda64recomp.json
Majora's Mask port
https://github.com/Zelda64Recomp/Zelda64Recomp
Repute: 6.3k stars on github
> zelda64recomp: Add version 1.2.0

- bucket/sm64coopdx.json
Adds manifest for sm64coopdx, a PC port of SM64 with multiplayer support
https://github.com/coop-deluxe/sm64coopdx
Repute: 684 stars on github
> sm64coopdx: Add version 1.3.2

- bucket/rpcs3.json
https://github.com/Calinou/scoop-games/actions/runs/15623733818/job/44013968223
> rpcs3: The remote server returned an error: (403) Forbidden.
> URL https://rpcs3.net/compatibility?b is not valid
- `rpcs3@0.0.37-18025`: Update url, fix checkver, fix autoupdate.
Closes #1454
Closes #1455
Closes #1461
> rpcs3@0.0.37-18025: Update url, fix checkver, fix autoupdate

- bucket/vkquake.json
https://github.com/Calinou/scoop-games/actions/runs/15838300168/job/44646253645
> vkquake: 1.32.3.1 (scoop version is 1.32.3) autoupdate available
> Autoupdating vkquake
> Downloading vkquake-1.32.3.1_win32.zip to compute hashes!
> The remote server returned an error: (404) Not Found.
> URL https://github.com/Novum/vkQuake/releases/download/1.32.3.1/vkquake-1.32.3.1_win32.zip is not valid
> ERROR Could not update vkquake, hash for vkquake-1.32.3.1_win32.zip failed!
- `vkquake`: Update to version 1.32.3.1, fix autoupdate.
> vkquake: Update to version 1.32.3.1, fix autoupdate

- bucket/modboy.json
https://github.com/Calinou/scoop-games/actions/runs/15623733818/job/44013968223
> InvalidOperation: 
> Line |
>    2 |  $getData = ((Invoke-RestMethod 'https://gamebanana.com/apiv10/Tool/63 …
>      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot index into a null array.
> modboy: couldn't match '(?<File>[\w_]+\.exe),\s([\d.]+)' in the output of script
- `modboy@3.11`: Fix checkver, fix autoupdate.
> modboy@3.11: Fix checkver, fix autoupdate

- bucket/rgbds.json
- `rgbds`: Update to version 0.9.3, fix autoupdate.
> rgbds: Update to version 0.9.3, fix autoupdate

- bucket/naev.json
- `naev`: Fix shortcut.
Closes #1472
> naev: Fix shortcut issue

- bucket/taisei.json
- `taisei`: Update to version 1.4.3, remove 32-bit arch, add hash extraction.
> osulazer: 2025.710.0 (scoop version is 2025.607.0) autoupdate available
> Autoupdating osulazer
> The remote server returned an error: (404) Not Found.
> URL https://github.com/ppy/osu/releases/download/2025.710.0/osulazer-2025.710.0-full.nupkg#/dl.7z is not valid
> ERROR Could not update osulazer, hash for osulazer-2025.710.0-full.nupkg failed!
`taisei` 32-bit x86 builds are [no longer provided](https://github.com/taisei-project/taisei/releases/tag/v1.4.3) for Windows.
> taisei: Update to version 1.4.3, remove 32-bit arch, add hash extraction

- bucket/osulazer.json
- `osulazer`: Update to version 2025.710.0-lazer, fix checkver.
> osulazer: 2025.710.0 (scoop version is 2025.607.0) autoupdate available
> Autoupdating osulazer
> Downloading osulazer-2025.710.0-full.nupkg to compute hashes!
> The remote server returned an error: (404) Not Found.
> URL https://github.com/ppy/osu/releases/download/2025.710.0/osulazer-2025.710.0-full.nupkg#/dl.7z is not valid
> ERROR Could not update osulazer, hash for osulazer-2025.710.0-full.nupkg failed!
> osulazer: Update to version 2025.710.0-lazer, fix checkver

- bucket/goggalaxy.json
- `goggalaxy`: Persist galaxy-2.0.db to avoid rescanning, remove hash extraction.
Relates to #1428
> goggalaxy: Persist galaxy-2.0.db to avoid rescanning, remove hash extraction

- bucket/playit.json
- `playit`:
- Update to version 0.16.2.
- Simplify the pre_install script.
- Fix autoupdate. Update the executable filename.
> playit: Update to version 0.16.2, simplify pre_install script, fix autoupdate

- bucket/snes9x-dev.json
- `snes9x-dev`: Update to version 1.63-1503, fix checkver.
> snes9x-dev: Update to version 1.63-1503, fix checkver

- bucket/asset-ripper.json
- `asset-ripper@1.3.2`:
- `Remove post_uninstall script`: The post_uninstall script was used to clean up shortcuts generated by Asset Ripper, but this cleanup process is now unnecessary.
- `Add persist`: Persist _AssetRipper.Settings.json_.
> asset-ripper@1.3.2: Remove post_uninstall script, add persist

- bucket/evemaptool.json
- `evemaptool@1.41`: Update repack url. 
Closes #1489
The CI may fail because the autoupdate URL is unreachable. But I still recommend keeping the original `autoupdate`, since this is a temporary change.
> evemaptool@1.41: Update repack url

- bucket/umodel.json
- `umodel`: Add version 2023.07.07.
Related issues:
- Closes #1246
> umodel: Add version 2023.07.07

- bucket/skyemu.json
This PR adds a manifest for **SkyEmu**, a fast, accurate, and lightweight emulator for GBA, GB, GBC, and experimental NDS support.
The manifest includes:
- Proper versioning (`4`) with GitHub `checkver` and `autoupdate`
- Persistent folders for `bios`, `cheats`, and `saves`
- Migration of old config data from `%APPDATA%` to Scoop's `persist` folder using junction
- Detailed usage notes for BIOS setup
Closes #1526
> Add SkyEmu emulator
